// Ported from reviews/sentence-bloom-web-2026-10-07/preview/sentence-bloom.js (Lea-Faka-Tonga working tree, approved at Step 6, 2026-10-08).
// Checked against: the site's book and lesson list at lea-faka-tonga-app origin/main d59d1e2037b179d91b57e5d7d804faef4dd4df98
// (see the header of src/data/sentence-bloom-data.js, which is generated by that folder's tools/build-data.mjs and never edited by hand).
// Changes in the port, and only these: the data import path; okinafy imported from the site (src/lib/okinafy.js) instead of a copy;
// the module's two literal colours (dark grey text and the road-stop ring) replaced by the site's --wr-ink and --line-strong;
// two unused variables removed for lint; a modified click on Start Lesson N (new tab, new window) is left to the browser instead of onNavigate; the separator in the data's `sources` strings is ' | ' instead of an em dash (see the data file's port note), and the regex that reads it follows; the English line is moved with a transform instead of `top`, so its jumps between lines of the sentence are not layout shifts (Core Web Vitals) on the live page.
// Sentence bloom for the homepage: a 25.18 s play that ends on the whole course, explorable lesson by lesson.
// 0 to 15.88 s: one sentence spins, turns and grows (Storyboard.json). From 15.88 s (Storyboard S5, approved 2026-10-08):
// the Lesson 9 page becomes a card on a stack, the stack deals out, a carousel pans across the 52 lessons, the row curves
// into the blueprint wheel, the wheel turns, counter-spins and unfolds into the course view (the site's six named parts).
// Self-contained ES module, no dependencies. mount(element, options) returns a controller; unmount() removes it.
// Look: the homepage's own tokens (--wr-*, --f-*, base.css); the blueprint keeps its ruled palette (#0d375c, #c4deff, #deecff).
// Every Tongan string comes from ./sentence-bloom-data.js (book rows found pair-level in both books, atlas-grammar labels
// with sources); lesson titles, topics and parts come from the site's chapters.json, verbatim (see the data file's header).
import DATA from '@app/data/sentence-bloom-data.js'
import { okinafy } from '@app/lib/okinafy.js'

// Development only: freeze the imported data, so any write into it throws instead of leaking state between mounts.
const DEV = (() => { try { if (import.meta.env) return !!import.meta.env.DEV } catch { /* not bundled */ } return typeof location !== 'undefined' && /^(localhost|127\.0\.0\.1)$/.test(location.hostname) })()
const deepFreeze = o => { if (o && typeof o === 'object' && !Object.isFrozen(o)) { Object.freeze(o); for (const v of Object.values(o)) deepFreeze(v) } return o }
if (DEV) deepFreeze(DATA)

const ROWS = DATA.rows, LESSONS = DATA.lessons, PLAY = DATA.play, END = PLAY.runtime, COURSE = DATA.course
const BEAT = Object.fromEntries(PLAY.ending.map(b => [b.id, b]))
const PAGE = PLAY.page
const BP = '#0d375c', RING = '#c4deff', BPINK = '#deecff'
const clamp = (x, a = 0, b = 1) => Math.max(a, Math.min(b, x))
const lerp = (a, b, e) => a + (b - a) * e
const E = u => 1 - Math.pow(1 - clamp(u), 2.4)
const smooth = u => { u = clamp(u); return u * u * (3 - 2 * u) }
const smoother = u => { u = clamp(u); return u * u * u * (u * (u * 6 - 15) + 10) }
const span = (a, b, t) => clamp((t - a) / (b - a))
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])
const h = (tag, cls, html) => { const e = document.createElement(tag); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e }
const srcText = i => (i == null ? '' : okinafy(DATA.sources[i].replace(/^book\/Chapter-0?(\d+)\.md:[\d,-]+ \| /, 'Lesson $1: ')))
// The site's display rule for the glottal stop (src/lib/okinafy.js) is imported above: the data stays verbatim from chapters.json
// (ASCII apostrophe, DECISIONS.md 2026-06-20) and display turns an apostrophe before a vowel into the fakauʻa ʻ (U+02BB).
// Lesson titles are not passed through it: the site prints c.title raw (Lessons.jsx, Lesson.jsx), so the card prints it raw too.
// Topics: Tongan words marked lang="to" as the site's Mixed component does (src/premium/pages/Lessons.jsx), with the
// term list and pattern of splitMixedTonganText in src/lib/lesson-browser.js at the same commit.
const MIXED_TONGAN_TERMS = [
  'fe-...-ʻaki', 'lolotonga', 'faka-', 'taʻe-', '-ʻanga', 'ngaahi', 'totonu',
  'ʻaʻaku', 'ʻoʻoku', 'ʻanefe', 'kapau', 'hingoā', 'mou', 'ʻikai', 'pehē',
  'ʻaupito', 'ʻofa', 'ʻosi', 'ʻeni', 'ʻena', 'ʻafe', 'ʻaki', 'lava', 'tuku',
  'kiate', 'meiate', 'fie', 'kuo', 'naʻa', 'naʻe', 'ʻoku', 'siʻi', 'siʻa',
  'fuʻu', 'kiʻi', 'meia', 'taha', 'ange', 'lolotonga', 'taʻu', 'fiha', 'nga',
  '-ʻi', '-nga', 'fe-', 'ʻia', 'faka-Tonga', 'ko', 'mo', 'ki', 'mei', 'ha',
  'ʻe', 'ʻa', 'ʻi', 'ʻo', 'ke', 'ku', 'te', 'e', 'he', 'ho', 'fie', 'kei',
  'pea', 'kau', 'mai', 'atu', 'ai', 'hai', 'fe', 'pau', 'ʻanga', 'loto', 'lalo', 'kia', 'ka', 'kita',
]
const MIXED_PATTERN = new RegExp(`(?<![\\p{L}\\p{M}])(${[...new Set(MIXED_TONGAN_TERMS)].sort((a, b) => b.length - a.length).map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replaceAll('ʻ', "[ʻ'‘’ʼ`]")).join('|')})(?![\\p{L}\\p{M}])`, 'giu')
const mixedHtml = text => {
  const t = okinafy(String(text ?? '')); let out = '', end = 0
  for (const m of t.matchAll(MIXED_PATTERN)) { out += esc(t.slice(end, m.index)) + `<span lang="to">${esc(m[0])}</span>`; end = m.index + m[0].length }
  return out + esc(t.slice(end))
}
const GROUP = Object.fromEntries(COURSE.groups.map(g => [g.key, okinafy(g.name)]))

// The beat table the module plays: the sentence's beats (Storyboard.json), then the ending (Storyboard S5, pan 1.5 s longer).
export const TIMELINE = (() => {
  const out = []
  for (const s of PLAY.segs) { const l = out[out.length - 1]; if (l && l.id === s.beat) l.end = s.t1; else out.push({ id: s.beat, start: s.t0, end: s.t1 }) }
  return Object.freeze([...out, ...PLAY.ending.map(b => ({ id: b.id, start: b.start, end: b.end }))].map(Object.freeze))
})()

// the carousel runs from the deal's last frame to the pan's: on desktop Lesson 3 to Lesson 50 in the red frame (S5 frames 3 and 4);
// a phone shows two cards side by side, so it runs from Lessons 1 and 2 to Lessons 51 and 52
const ROT_TURN = 36, ROT_BACK = 110
const dealStart = n => BEAT.deal.start + (n <= 7 ? (n - 1) * 0.035 : 0.24)
const chipStart = n => BEAT.counter.start + 0.15 + (n - 1) / 51 * 0.75
const CHIP_FLY = 0.3
const stackDepth = n => (n === 9 ? 0 : n < 9 ? clamp(8 - n, 1, 7) : 7)

const CSS = `
.sb{position:relative;font-family:var(--f-ui);color:var(--wr-ink);--sbk:1}
.sb *{box-sizing:border-box}
.sb [lang="to"]{font-family:var(--f-serif);font-style:italic;font-weight:450}
.sb-panel{position:relative;border-radius:2px;padding:18px 24px 22px}
.sb-ground{position:absolute;inset:0;border-radius:2px;background-color:${BP};background-image:linear-gradient(rgba(196,222,255,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(196,222,255,.16) 1px,transparent 1px),linear-gradient(rgba(196,222,255,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(196,222,255,.07) 1px,transparent 1px);background-size:120px 120px,120px 120px,24px 24px,24px 24px;opacity:0;pointer-events:none}
.sb-top{position:relative;z-index:3;display:flex;flex-wrap:wrap;align-items:flex-end;justify-content:space-between;gap:10px 16px;padding:0 0 6px}
.sb-flag{display:flex;align-items:baseline;gap:8px;white-space:nowrap}
.sb-flag .k{font:800 15px/1 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:var(--wr-red)}
.sb-flag .n{font:800 64px/.8 var(--f-display);color:var(--wr-red)}
.sb-flag .of{font:700 18px/1 var(--f-display);letter-spacing:.06em;text-transform:uppercase;color:var(--wr-muted)}
.sb-bphead .eb{margin:0 0 6px;color:${RING};font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}
.sb-bphead h3{margin:0;font:800 40px/.92 var(--f-display);letter-spacing:-.005em;text-transform:uppercase;color:#fff}
.sb-hd{display:grid;min-width:0;min-height:62px;align-items:end}
.sb-hd>*{grid-area:1/1}
.sb-hd>[hidden]{display:none}
.sb-ctl{display:flex;flex-wrap:wrap;gap:8px;flex-shrink:0}
.sb-btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 14px;border:1px solid var(--home-rule,#cfcfcf);border-radius:2px;background:#fff;color:var(--wr-ink);font:600 13px/1.1 var(--f-ui);cursor:pointer;white-space:nowrap}
.sb-btn:hover{border-color:var(--wr-red);color:var(--wr-red-deep)}
.sb-btn[hidden]{display:none}
.sb :focus-visible{outline:3px solid var(--wr-red-deep);outline-offset:3px;border-radius:2px}
.sb.is-dark .sb-top .sb-btn{background:transparent;color:${BPINK};border-color:rgba(196,222,255,.5)}
.sb.is-dark .sb-top .sb-btn:hover{color:#fff;border-color:#fff}
.sb.is-dark .sb-top :focus-visible,.sb.is-dark .sb-course :focus-visible{outline-color:#fff}
.sb.is-dark .sb-course .sb-ls:focus-visible{box-shadow:0 0 0 6px ${BP}}
.sb-stage{position:relative;z-index:1;overflow:hidden}
.sb-sent{position:absolute;inset:0;pointer-events:none}
.sb-en{position:absolute;left:0;right:0;top:0;margin:0}
.sb-en p{position:absolute;left:0;right:0;margin:0 auto;padding:0 8px;text-align:center;font-size:33px;line-height:1.2;color:var(--wr-ink);will-change:transform,opacity}
.sb-line{position:absolute;left:0;right:0;top:0}
.sb-cell{position:absolute;top:0;perspective:760px}
.sb-cell.drum::after{content:'';position:absolute;inset:-6px;border:3px solid var(--wr-red);border-radius:3px;transform:translateZ(2px) scale(var(--sbk));pointer-events:none}
.sb-face{position:absolute;left:0;top:0;display:grid;grid-template-rows:auto 1fr;padding:11px 18px 13px;background:#fff;border:1px solid var(--line-strong,#d3cdc4);border-bottom:3px solid var(--wr-red);border-radius:2px;box-shadow:0 10px 20px -17px rgba(35,22,16,.9);backface-visibility:hidden;white-space:nowrap}
.sb-face.off{background:var(--paper-soft,#f7f5f2);box-shadow:none}
.sb-face.new{background:color-mix(in srgb,var(--wr-red-pale) 35%,#fff)}
.sb-lab{color:var(--wr-red-deep);font:750 12px/1.1 var(--f-display);letter-spacing:.14em;text-transform:uppercase}
.sb-lab.none{visibility:hidden}
.sb-w{margin-top:6px;font-size:56px;line-height:1.05;align-self:end}
.sb-punct{position:absolute;top:0;font:italic 48px/1 var(--f-serif)}
.sb-more{position:absolute;right:0;margin:0;font:700 18px/1 var(--f-display);letter-spacing:.08em;text-transform:uppercase;color:var(--wr-muted)}
.sb-links{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}
.sb-links path{fill:none;stroke:var(--wr-red);stroke-width:1.5;stroke-dasharray:2 4;opacity:.9}
.sb-road{position:absolute;left:0;right:0;bottom:0;height:44px;display:flex;justify-content:space-between;align-items:flex-start;padding:0 2px}
.sb-road::before{content:'';position:absolute;left:0;right:0;top:6px;height:3px;background:var(--line-strong,#d3cdc4)}
.sb-stop{position:relative;width:14px;display:flex;flex-direction:column;align-items:center}
.sb-stop i{position:relative;z-index:1;width:9px;height:9px;margin-top:3px;border-radius:50%;background:#fff;border:2px solid var(--line-strong)}
.sb-stop.done i{background:var(--wr-red);border-color:var(--wr-red)}
.sb-stop.now i{width:17px;height:17px;margin-top:-1px;background:#fff;border:5px solid var(--wr-red)}
.sb-stop b{position:absolute;top:20px;font:800 14px/1 var(--f-display);color:var(--wr-muted)}
.sb-stop.done b{color:var(--wr-red)}
.sb-stop.now b{top:22px;font-size:18px;color:var(--wr-red-deep)}
.sb-gap{flex:0 0 26px;position:relative;z-index:1;height:15px;background:repeating-linear-gradient(90deg,transparent 0 4px,#fff 4px 8px)}
.sb-cards,.sb-labs{position:absolute;inset:0;pointer-events:none}
.sb-card{position:absolute;left:0;top:0;display:flex;flex-direction:column;align-items:center;padding:14px 12px 44px;background:#fff;border:1px solid var(--line-strong,#d3cdc4);border-top:5px solid var(--wr-red);box-shadow:0 14px 24px -20px rgba(35,22,16,.75);text-align:center;transform-origin:50% 50%;visibility:hidden;opacity:0}
.sb-ck{align-self:flex-start;display:flex;align-items:baseline;gap:6px;font-family:var(--f-display);color:var(--wr-red);white-space:nowrap}
.sb-ck b{font-weight:800;font-size:12px;letter-spacing:.18em;text-transform:uppercase}
.sb-ck i{font-style:normal;font-weight:800;font-size:38px;line-height:.85}
.sb-cto{display:block;margin-top:auto;font-size:21px;line-height:1.14}
.sb-cen{display:block;margin:7px 0 auto;font-size:13px;line-height:1.3;color:var(--wr-muted)}
.sb-cr{position:absolute;left:0;right:0;bottom:20px;height:2px;background:var(--wr-red-pale)}
.sb-cr i{position:absolute;left:50%;top:-6px;width:14px;height:14px;margin-left:-7px;border-radius:50%;background:#fff;border:3px solid var(--wr-red-pale)}
.sb-card.cur{box-shadow:0 0 0 4px var(--wr-red),0 14px 24px -20px rgba(35,22,16,.75)}
.sb-card.cur .sb-cr{background:var(--wr-red)}
.sb-card.cur .sb-cr i{border-color:var(--wr-red)}
.sb-card.bp{background:${BP};border-color:rgba(196,222,255,.7);border-top-color:${RING};color:${BPINK};box-shadow:none}
.sb-card.bp .sb-ck,.sb-card.bp .sb-cen{color:${BPINK}}
.sb-card.bp .sb-cr{background:rgba(196,222,255,.5)}
.sb-card.bp .sb-cr i{background:${BP};border-color:${RING}}
.sb-wheel{position:absolute;left:0;top:0;overflow:visible;pointer-events:none}
.sb-rim{font:700 9.5px/1 var(--f-display);letter-spacing:.12em;fill:${BPINK};text-transform:uppercase}
.sb-orb{font:italic 450 14px var(--f-serif);fill:${BPINK};word-spacing:.15em}
.sb-lc{position:absolute;border:1px solid rgba(196,222,255,.7);background:rgba(13,55,92,.95);color:${BPINK};padding:10px 12px;visibility:hidden;opacity:0}
.sb .sb-lck{margin:0 0 8px;font:700 11px/1 var(--f-display);letter-spacing:.16em;text-transform:uppercase}
.sb-lws{list-style:none;margin:0;padding:0;display:flex;gap:6px;align-items:flex-start}
.sb-lc .sb-part{display:flex;flex-direction:column;align-items:center;gap:5px}
.sb-lc .sb-part [lang="to"]{border:1px solid rgba(196,222,255,.8);padding:2px 6px;font-size:21px;line-height:1.1;white-space:nowrap}
.sb-lc .sb-lab{color:${BPINK};font:700 9px/1.05 var(--f-display);letter-spacing:.1em;max-width:96px;text-align:center}
.sb-lp{font:italic 21px/1.1 var(--f-serif);padding-top:3px}
.sb .sb-le{margin:9px 0 0;font-size:13px;line-height:1.3;text-align:center}
.sb-course{position:relative;padding:10px 8px 14px;visibility:hidden;opacity:0;color:${BPINK}}
.sb-croad{position:absolute;left:0;top:0;overflow:visible;pointer-events:none}
.sb-croad path{fill:none;stroke:${RING};stroke-width:2;stroke-opacity:.7}
.sb .sb-hintc{position:relative;margin:0 0 14px;font:700 13px/1.2 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:${BPINK}}
.sb-grp{position:relative;display:grid;grid-template-columns:120px 1fr;column-gap:16px;align-items:start;margin:0 0 20px}
.sb-grp:last-child{margin-bottom:0}
.sb .sb-gname{margin:6px 0 0;font:700 13px/1.1 var(--f-display);letter-spacing:.12em;text-transform:uppercase;color:${BPINK}}
.sb-row{position:relative;display:flex;justify-content:space-between;align-items:flex-start}
.sb:not(.is-sheet) .sb-rows{padding-right:26px}
.sb-ls{position:relative;display:flex;flex-direction:column;align-items:center;min-width:44px;min-height:44px;margin:0;padding:0;border:0;background:none;color:${BPINK};font:inherit;cursor:pointer}
.sb-chip{display:block;width:28px;height:28px;border-radius:50%;border:1.5px solid ${RING};background:${BP};font:800 14px/25px var(--f-display);text-align:center;color:${BPINK}}
.sb-ttl{display:block;margin-top:5px;font:400 10.5px/1.15 var(--f-ui);text-align:center;hyphens:auto;-webkit-hyphens:auto}
.sb-ls:hover .sb-chip{border-color:#fff;color:#fff}
.sb-ls:hover .sb-ttl{color:#fff;text-decoration:underline}
.sb-ls[aria-expanded="true"] .sb-chip{background:#fff;color:${BP};border-color:#fff;box-shadow:0 0 0 4px rgba(255,255,255,.25)}
.sb.has-pv.is-docked .sb-ls:not([aria-expanded="true"]),.sb.has-pv.is-docked .sb-gname,.sb.has-pv.is-docked .sb-hintc{opacity:.65}
.sb.is-sheet .sb-grp{display:block;margin-bottom:14px}
.sb.is-sheet .sb-gname{margin:0 0 6px;padding-left:30px}
.sb.is-sheet .sb-row{justify-content:flex-start;margin-bottom:8px}
.sb.is-sheet .sb-ls{width:44px;height:44px;justify-content:center}
.sb.is-sheet .sb-chip{width:36px;height:36px;font-size:15px;line-height:33px}
.sb-pv{position:absolute;z-index:4;width:460px;background:#fff;color:var(--wr-ink);border-top:6px solid var(--wr-red);padding:18px 22px 16px;box-shadow:var(--shadow-3,0 30px 70px -20px rgba(0,0,0,.5));border-radius:2px}
.sb-pv[hidden]{display:none}
.sb .sb-pv-h{margin:0 44px 0 0;outline-offset:4px}
.sb-pv-e{display:flex;flex-wrap:wrap;gap:4px 10px;font:700 15px/1.1 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:var(--wr-red)}
.sb-pv-g{color:var(--wr-muted)}
.sb-pv-t{display:block;margin-top:5px;font:800 32px/1 var(--f-display);color:var(--wr-ink)}
.sb .sb-pv-sec{margin:13px 0 0;font:700 12px/1.1 var(--f-display);letter-spacing:.16em;text-transform:uppercase;color:var(--wr-muted)}
.sb .sb-pv ul{list-style:none;margin:6px 0 0;padding:0}
.sb-pv li{position:relative;padding-left:16px;font-size:14.5px;line-height:1.3}
.sb-pv li::before{content:'';position:absolute;left:0;top:.62em;width:8px;height:2px;background:var(--wr-red)}
.sb .sb-pv-by{margin:13px 0 0;font-size:14.5px;font-weight:600;line-height:1.3}
.sb .sb-pv-ex{margin:7px 0 0}
.sb-pv-ex [lang="to"]{display:block;font-size:20px;line-height:1.15}
.sb-pv-ex .e{display:block;margin-top:1px;font-size:13.5px;line-height:1.3;color:var(--wr-muted)}
.sb-close{position:absolute;right:8px;top:8px;width:44px;height:44px;display:flex;align-items:center;justify-content:center;border:0;background:transparent;color:var(--wr-ink);font:400 26px/1 var(--f-ui);cursor:pointer;border-radius:2px}
.sb-close:hover{color:var(--wr-red-deep)}
.sb-nav{display:flex;align-items:stretch;gap:8px;margin:14px 0 0}
.sb-nav .sb-start{flex:1}
.sb-nav .sb-btn{background:#fff;color:var(--wr-ink);border-color:var(--home-rule,#cfcfcf)}
.sb-nav .sb-btn[hidden]{display:inline-flex;visibility:hidden}
.sb-start{display:flex;align-items:center;justify-content:center;min-height:48px;padding:0 10px;text-align:center;color:#fff;background:var(--wr-red);font-size:16px;font-weight:800;letter-spacing:.02em;border-radius:2px;text-decoration:none}
.sb-start:hover{background:var(--wr-red-deep)}
.sb .sb-pv :focus-visible,.sb.is-dark .sb-course .sb-pv :focus-visible{outline-color:var(--wr-red-deep)}
.sb .sb-keys{margin:8px 0 0;font-size:12px;color:var(--wr-muted);text-align:center}
.sb-sr{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}
.sb-measure{position:absolute;left:-9999px;top:0;visibility:hidden}
.sb.is-sheet .sb-pv{position:relative;width:auto;margin:2px 0 16px;padding:16px 16px 14px;box-shadow:0 18px 40px -18px rgba(0,0,0,.6)}
.sb.is-sheet .sb-pv-t{font-size:28px}
.sb.is-sheet .sb-pv li{font-size:14px}
.sb.is-sheet .sb-pv-by{font-size:14px}
.sb.is-sheet .sb-pv-ex [lang="to"]{font-size:19px}
.sb.is-sheet .sb-nav{flex-wrap:wrap}
.sb.is-sheet .sb-nav .sb-start{order:3;flex-basis:100%}
.sb.is-sheet .sb-nav [data-go="1"]{margin-left:auto}
.sb.is-narrow .sb-nav .sb-btn{padding:0 8px;font-size:12px}
.sb.is-narrow .sb-start{font-size:14px}
.sb.is-sheet .sb-keys{display:none}
.sb.is-narrow .sb-panel{padding:12px 6px 14px}
.sb.is-narrow .sb-hd{min-height:56px}
.sb.is-narrow .sb-ctl{width:100%}
.sb.is-narrow .sb-flag .n{font-size:46px}
.sb.is-narrow .sb-flag .k{font-size:12px}
.sb.is-narrow .sb-flag .of{font-size:14px}
.sb.is-narrow .sb-btn{padding:0 10px;font-size:12.5px}
.sb.is-narrow .sb-bphead h3{font-size:25px}
.sb.is-narrow .sb-en p{font-size:27px}
.sb.is-narrow .sb-face{padding:7px 9px 8px}
.sb.is-narrow .sb-lab{font-size:9px;letter-spacing:.08em}
.sb.is-narrow .sb-face .sb-lab{white-space:normal;max-width:72px;line-height:1.15}
.sb.is-narrow .sb-w{margin-top:3px;font-size:30px}
.sb.is-narrow .sb-punct{font-size:28px}
.sb.is-narrow .sb-more{right:auto;left:0;text-align:left;font-size:14px}
.sb.is-narrow .sb-links{z-index:-1}
.sb.is-narrow .sb-stop b{font-size:11px}
.sb.is-narrow .sb-stop.now b{font-size:14px}
.sb.is-narrow .sb-rim{font-size:9px;letter-spacing:0}
.sb.is-narrow .sb-orb{font-size:12px}
.sb.is-narrow .sb-lc .sb-part [lang="to"]{font-size:17px;padding:2px 5px}
.sb.is-narrow .sb-lp{font-size:17px}
.sb.is-narrow .sb-course{padding:8px 4px 10px}
.sb.is-narrow .sb-card{padding:10px 8px 36px}
.sb.is-narrow .sb-ck i{font-size:30px}
.sb.is-narrow .sb-ck b{font-size:10px}
.sb.is-narrow .sb-cto{font-size:17px}
.sb.is-narrow .sb-cen{font-size:12px}
.sb.is-tiny .sb-w{font-size:26px}
.sb.is-tiny .sb-face{padding:6px 7px 7px}
.sb.is-tiny .sb-lab{font-size:8px;letter-spacing:.06em}
.sb.is-tiny .sb-btn{padding:0 8px;font-size:12px}
@media (hover:none){.sb-keys{display:none}}
@media (prefers-reduced-motion:reduce){.sb *{transition:none!important;animation:none!important}}
`

let styleEl = null, styleRefs = 0, uid = 0
const instances = new Set()

export function mount(el, options = {}) {
  if (!el) throw new Error('mount needs an element')
  for (const inst of instances) if (inst.el === el) inst.destroy()
  const opt = {
    lessonHref: n => `/lessons/${n}`,
    onNavigate: null,
    startRatio: 0.6,
    ...options,
  }
  const mq = typeof matchMedia === 'function' ? matchMedia('(prefers-reduced-motion: reduce)') : null
  const reduced = opt.reducedMotion ?? (mq ? mq.matches : false)

  if (!styleEl) { styleEl = document.createElement('style'); styleEl.setAttribute('data-sentence-bloom', ''); styleEl.textContent = CSS; document.head.appendChild(styleEl) }
  styleRefs++

  // ---------- DOM ----------
  const root = h('div', 'sb')
  root.setAttribute('role', 'group')
  root.setAttribute('aria-label', 'A preview of the course: one sentence grows lesson by lesson, then all 52 lessons, each one open to preview')
  const panel = h('div', 'sb-panel')
  const ground = h('div', 'sb-ground'); ground.setAttribute('aria-hidden', 'true')
  const top = h('div', 'sb-top')
  const hd = h('div', 'sb-hd')
  const flag = h('div', 'sb-flag', '<span class="k">Lesson</span><span class="n">2</span><span class="of">of 52</span>')
  flag.setAttribute('aria-hidden', 'true')
  const bphead = h('div', 'sb-bphead', '<p class="eb">The blueprint</p><h3>Lessons 1 to 52, sentence by sentence.</h3>')
  bphead.setAttribute('aria-hidden', 'true')
  const chead = h('div', 'sb-bphead', '<p class="eb">The course</p><h3>Lessons 1 to 52, in order.</h3>')
  hd.append(flag, bphead, chead)
  const ctl = h('div', 'sb-ctl')
  const bPause = h('button', 'sb-btn', 'Pause'); bPause.type = 'button'
  const bReplay = h('button', 'sb-btn', 'Replay'); bReplay.type = 'button'
  const bSkip = h('button', 'sb-btn', 'Skip to the course view'); bSkip.type = 'button'
  ctl.append(bPause, bReplay, bSkip)
  top.append(hd, ctl)
  const stage = h('div', 'sb-stage')
  const sent = h('div', 'sb-sent'); sent.setAttribute('aria-hidden', 'true')
  const enBox = h('div', 'sb-en'), line = h('div', 'sb-line'), more = h('p', 'sb-more', 'Then on to Lesson 52.')
  sent.append(enBox, line, more)
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('class', 'sb-links'); svg.setAttribute('aria-hidden', 'true')
  const road = h('div', 'sb-road'); road.setAttribute('aria-hidden', 'true')
  const STOPS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 'gap', 52]
  road.innerHTML = STOPS.map(n => n === 'gap' ? '<span class="sb-gap"></span>' : `<span class="sb-stop" data-n="${n}"><i></i>${[1, 2, 3, 4, 9, 52].includes(n) ? `<b>${n}</b>` : `<b class="opt">${n}</b>`}</span>`).join('')
  // the ending's layers: the cards (stack, deal, carousel, curve), the wheel, the part cards beside it, the course view
  const cardsEl = h('div', 'sb-cards'); cardsEl.setAttribute('aria-hidden', 'true')
  const cards = LESSONS.map(L => {
    const r = ROWS[L.card]
    const c = h('div', 'sb-card', `<span class="sb-ck"><b>Lesson</b><i>${L.n}</i></span><span class="sb-cto" lang="to" data-row="${r.id}">${esc(r.to)}</span><span class="sb-cen" data-row="${r.id}">${esc(r.en)}</span><span class="sb-cr"><i></i></span>`)
    c.dataset.n = L.n; cardsEl.append(c); return c
  })
  const wheel = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); wheel.setAttribute('class', 'sb-wheel'); wheel.setAttribute('aria-hidden', 'true')
  wheel.style.visibility = 'hidden'; wheel.style.opacity = 0
  const labsEl = h('div', 'sb-labs'); labsEl.setAttribute('aria-hidden', 'true')
  const course = h('div', 'sb-course'); course.setAttribute('role', 'group'); course.setAttribute('aria-label', 'The 52 lessons, in six parts')
  stage.append(sent, svg, road, cardsEl, wheel, labsEl, course)
  panel.append(ground, top, stage)
  const pv = h('aside', 'sb-pv')
  pv.setAttribute('aria-labelledby', 'sb-pv-h-' + (++uid))
  pv.hidden = true
  const live = h('div', 'sb-sr'); live.setAttribute('aria-live', 'polite')
  const measure = h('div', 'sb-measure'); measure.setAttribute('aria-hidden', 'true')
  root.append(panel, pv, live, measure)
  el.append(root)
  const pvId = pv.getAttribute('aria-labelledby')

  // the part cards beside the wheel: Lesson 2 and Lesson 4, every word with its recorded label and source
  const labCard = id => {
    const r = ROWS[id]
    const ws = r.words.map(w => `<li class="sb-part"><span lang="to" data-row="${r.id}">${esc(w[0])}</span>${w[1] ? `<span class="sb-lab" data-src="${esc(srcText(w[2]))}" title="${esc(srcText(w[2]))}">${esc(w[1])}</span>` : ''}</li>`).join('')
    const c = h('div', 'sb-lc', `<p class="sb-lck">Lesson ${r.lesson}</p><ul class="sb-lws">${ws}<li class="sb-lp">${esc(r.punct)}</li></ul><p class="sb-le" data-row="${r.id}">${esc(r.en)}</p>`)
    labsEl.append(c); return c
  }
  const labs = DATA.lab_rows.map(labCard)

  // ---------- state ----------
  let t = 0, mode = reduced ? 'end' : 'play', playing = false, userPaused = false, autoPaused = false, inView = false
  let raf = 0, last = 0, W = 0, wcls = '', geo = null, segIdx = -1, seg = null, selected = 0, pvOpen = false, destroyed = false
  let chips = [], courseKey = '', chipPos = [], wheelG = null, rimEls = [], orbEls = []
  const rafReq = cb => (raf = requestAnimationFrame(cb))

  // ---------- geometry ----------
  function classify() {
    W = stage.clientWidth || root.clientWidth || 1
    const c = W >= 900 ? 'wide' : W >= 600 ? 'mid' : 'narrow'
    root.classList.toggle('is-narrow', c === 'narrow')
    root.classList.toggle('is-tiny', W < 340)
    wcls = c
    const narrow = c === 'narrow', courseWide = c === 'wide'
    root.classList.toggle('is-sheet', !courseWide)
    const perRow = Math.max(4, Math.floor((W - 8 + 10) / (44 + 10)))
    geo = { c, narrow, courseWide, perRow, playH: c === 'wide' ? 560 : c === 'mid' ? 520 : 470, roadH: 44 }
    // the carousel's cards: one size, as tall as the tallest card's content at that width
    // the fade band at the stage's edges: a card fades out before any of it can be cut by the edge
    geo.gap = narrow ? 12 : 18; geo.band = narrow ? 8 : 26
    geo.cw = narrow ? Math.floor((W - geo.gap - 2 * (geo.band + 4)) / 2) : 200
    geo.sp = geo.cw + geo.gap
    cards.forEach(cd => { cd.style.width = geo.cw + 'px'; cd.style.height = '' })
    let chMax = 0
    for (const cd of cards) { cd.style.transform = 'none'; chMax = Math.max(chMax, cd.offsetHeight) }
    geo.ch = Math.ceil(Math.max(chMax, geo.cw * (narrow ? 1.2 : 1.35)))
    geo.C0 = narrow ? 1.5 : 3; geo.C1 = narrow ? 51.5 : 50
    // the bend lands the pan's last frame on top of the ring, so Lesson 1 sits that many steps clockwise of the top
    geo.rot0 = ((((1 - geo.C1) % 52) + 52) % 52) * 360 / 52
    cards.forEach(cd => { cd.style.height = geo.ch + 'px' })
    buildCourse()
    layoutCourse()
    // desktop keeps one stage height for the whole play and the ending: the play's, the course view's or the tallest preview card's
    if (courseWide) geo.playH = Math.max(geo.playH, geo.courseH, measurePvMax() + 16)
    geo.H = geo.playH
    geo.rowCy = (narrow ? geo.playH - 20 : geo.playH) / 2
    const pageW = narrow ? W * 0.78 : Math.min(W * 0.42, 460)
    geo.sPage = Math.min(pageW / geo.cw, (geo.playH - 70) / geo.ch)
    // the wheel: v5's blueprint, the lessons round the rim; on desktop the part cards sit to its left
    geo.side = W >= 1000
    if (geo.side) { geo.R = Math.min(215, geo.H / 2 - 72); geo.wcx = W * 0.64; geo.wcy = geo.H / 2; geo.rimOut = 61 }
    else { geo.R = Math.min(118, W / 2 - 34); geo.wcx = W / 2; geo.wcy = 18 + geo.R + 26; geo.rimOut = 24 }
    buildWheel()
    placeLabs()
    if (pvOpen) renderPv(false)
  }
  function measurePvMax() {
    if (!geo.courseWide) return 0
    const keep = { sel: selected, open: pvOpen, hidden: pv.hidden, vis: pv.style.visibility }
    pv.hidden = false; pv.style.visibility = 'hidden'
    let mx = 0
    for (const L of LESSONS) { pv.innerHTML = pvHtml(L.n); mx = Math.max(mx, pv.offsetHeight) }
    pv.style.visibility = keep.vis; pv.hidden = keep.hidden
    if (keep.open) pv.innerHTML = pvHtml(keep.sel)
    return mx
  }

  // ---------- the course view: the site's six named parts, every row left to right ----------
  function buildCourse() {
    const key = geo.courseWide ? 'w' : 'n' + geo.perRow
    if (courseKey === key) return
    courseKey = key
    if (pv.parentNode !== root) root.insertBefore(pv, live)
    course.innerHTML = ''
    const roadSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); roadSvg.setAttribute('class', 'sb-croad'); roadSvg.setAttribute('aria-hidden', 'true')
    const hint = h('p', 'sb-hintc', geo.courseWide ? 'Click a lesson to see what it teaches.' : 'Tap a lesson to see what it teaches.')
    course.append(roadSvg, hint)
    chips = []
    for (const G of COURSE.groups) {
      const grp = h('div', 'sb-grp'); grp.setAttribute('role', 'group'); grp.setAttribute('aria-label', okinafy(G.name)); grp.dataset.group = G.key
      const nm = h('p', 'sb-gname', esc(okinafy(G.name))); nm.setAttribute('aria-hidden', 'true')
      const box = h('div', 'sb-rows')
      const per = geo.courseWide ? G.lessons.length : geo.perRow
      for (let i = 0; i < G.lessons.length; i += per) {
        const row = h('div', 'sb-row')
        for (const n of G.lessons.slice(i, i + per)) {
          const L = LESSONS[n - 1]
          const b = h('button', 'sb-ls', `<span class="sb-chip" aria-hidden="true">${n}</span>${geo.courseWide ? `<span class="sb-ttl" lang="en" aria-hidden="true">${esc(L.title)}</span>` : ''}`)
          b.type = 'button'; b.dataset.n = n
          b.setAttribute('aria-label', `Lesson ${n}: ${L.title}`)
          b.setAttribute('aria-expanded', 'false')
          row.append(b); chips[n - 1] = b
        }
        box.append(row)
      }
      grp.append(nm, box); course.append(grp)
    }
    course._road = roadSvg
  }
  // measured once per width: where each chip sits, the road through them, and the course view's height
  function layoutCourse() {
    const wasOpen = pv.parentNode === course || (pv.parentNode && pv.parentNode.closest && pv.parentNode.closest('.sb-course'))
    if (wasOpen) root.insertBefore(pv, live)
    chips.forEach(b => { b.firstChild.style.transform = '' })
    const rowsEls = [...course.querySelectorAll('.sb-row')]
    if (geo.courseWide) {
      const trackW = course.clientWidth - 16 - 120 - 16 - 26
      for (const row of rowsEls) { const n = row.children.length, tw = Math.max(44, Math.min(112, Math.floor(trackW / n) - 4)); for (const b of row.children) b.style.width = tw + 'px'; row.style.gap = '' }
    } else {
      const cw = course.clientWidth - 8, per = geo.perRow, g = per > 1 ? Math.min(14, Math.floor((cw - per * 44) / (per - 1))) : 0
      for (const row of rowsEls) { row.style.gap = g + 'px'; for (const b of row.children) b.style.width = '' }
    }
    const cr = course.getBoundingClientRect(), sr = stage.getBoundingClientRect()
    const offX = cr.left - sr.left, offY = cr.top - sr.top
    chipPos = chips.map(b => { const r = b.firstChild.getBoundingClientRect(); return { x: r.left + r.width / 2 - cr.left, y: r.top + r.height / 2 - cr.top } })
    geo.courseOff = { x: offX, y: offY }
    // the road: along each row, then back under it to the next row's first lesson, like a line of text
    let d = ''
    const rows = rowsEls.map(row => { const ns = [...row.children].map(b => +b.dataset.n); const rr = row.getBoundingClientRect(); return { ns, bottom: rr.bottom - cr.top } })
    rows.forEach((r, i) => {
      const a = chipPos[r.ns[0] - 1], b = chipPos[r.ns[r.ns.length - 1] - 1]
      d += `M${a.x.toFixed(1)} ${a.y.toFixed(1)} L${b.x.toFixed(1)} ${b.y.toFixed(1)} `
      const nx = rows[i + 1]
      if (nx) {
        // desktop: the turn runs down beside the last title, not through it
        const c = chipPos[nx.ns[0] - 1], gy = r.bottom + (geo.courseWide ? 9 : 4), bend = geo.courseWide ? 18 : 12
        const lastB = chips[r.ns[r.ns.length - 1] - 1], xr = geo.courseWide ? b.x + lastB.offsetWidth / 2 + 12 : b.x + bend
        d += `M${b.x.toFixed(1)} ${b.y.toFixed(1)} L${(xr - 10).toFixed(1)} ${b.y.toFixed(1)} Q${xr.toFixed(1)} ${b.y.toFixed(1)} ${xr.toFixed(1)} ${(b.y + 10).toFixed(1)} L${xr.toFixed(1)} ${(gy - 10).toFixed(1)} Q${xr.toFixed(1)} ${gy.toFixed(1)} ${(xr - 10).toFixed(1)} ${gy.toFixed(1)} L${c.x.toFixed(1)} ${gy.toFixed(1)} C${(c.x - bend).toFixed(1)} ${gy.toFixed(1)} ${(c.x - bend).toFixed(1)} ${c.y.toFixed(1)} ${c.x.toFixed(1)} ${c.y.toFixed(1)} `
      }
    })
    const rs = course._road
    rs.setAttribute('width', Math.ceil(cr.width)); rs.setAttribute('height', Math.ceil(cr.height))
    rs.innerHTML = `<path d="${d}"/>`
    geo.courseH = Math.ceil(course.offsetHeight)
    geo.rowsOf = rows.map(r => r.ns)
    if (wasOpen && pvOpen) placePv()
  }

  // ---------- the wheel ----------
  const SVGNS = 'http://www.w3.org/2000/svg'
  const pol = (cx, cy, r, deg) => [cx + r * Math.sin(deg * Math.PI / 180), cy - r * Math.cos(deg * Math.PI / 180)]
  const arcPath = (cx, cy, r, a0, a1) => { const [x0, y0] = pol(cx, cy, r, a0), [x1, y1] = pol(cx, cy, r, a1); const large = Math.abs(a1 - a0) > 180 ? 1 : 0, sweep = a1 > a0 ? 1 : 0; return `M${x0.toFixed(1)},${y0.toFixed(1)} A${r.toFixed(1)},${r.toFixed(1)} 0 ${large} ${sweep} ${x1.toFixed(1)},${y1.toFixed(1)}` }
  function buildWheel() {
    const R = geo.R, cx = geo.wcx, cy = geo.wcy, side = geo.side
    wheel.setAttribute('width', Math.ceil(W)); wheel.setAttribute('height', Math.ceil(geo.H))
    const out = []
    const pid = 'sbw' + uid + '-' + (++wheelBuilds)
    out.push(`<g class="sb-wscale">`)
    for (let r = 34; r <= R; r += side ? 9 : 7) out.push(`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${RING}" stroke-opacity="${r + (side ? 9 : 7) > R ? .9 : .16}" stroke-width="${r + (side ? 9 : 7) > R ? 1.4 : .8}"/>`)
    out.push(`<circle cx="${cx}" cy="${cy}" r="${R + 4}" fill="none" stroke="${RING}" stroke-opacity=".5"/>`)
    out.push(`<g class="sb-wrot">`)
    for (let i = 0; i < 52; i++) {
      const a = i * 360 / 52, [x0, y0] = pol(cx, cy, R, a), [x1, y1] = pol(cx, cy, R + 6, a)
      out.push(`<line x1="${x0.toFixed(1)}" y1="${y0.toFixed(1)}" x2="${x1.toFixed(1)}" y2="${y1.toFixed(1)}" stroke="${RING}" stroke-opacity=".8"/>`)
    }
    // one point per sentence in the data, at its lesson's angle
    for (const L of LESSONS) [L.card, ...L.preview.filter(id => id !== L.card)].forEach((id, k) => {
      const a = (L.n - 1) * 360 / 52 + (k % 2 ? 2.2 : -2.2) * Math.ceil(k / 2), rr = R * (0.3 + 0.62 * ((L.n * 7 + k * 13) % 23) / 23)
      const [x, y] = pol(cx, cy, rr, a)
      out.push(`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${side ? 2 : 1.5}" fill="${BPINK}" fill-opacity=".85"/>`)
    })
    // sentences riding the wheel, upright where they start: clockwise over the top half, reversed under the bottom
    const px = side ? 14 : 12
    ;(side ? PLAY.orbits.wide : PLAY.orbits.narrow).forEach(([n, f, a], j) => {
      const r = ROWS[LESSONS[n - 1].card], rr = R * f
      const len = r.to.length * px * 0.56 * 1.6, sp = Math.min(300, len / rr * 180 / Math.PI)
      const scr = ((a + geo.rot0) % 360 + 360) % 360, bottom = scr > 90 && scr < 270
      const d = bottom ? arcPath(cx, cy, rr + px * 0.7, a + sp / 2, a - sp / 2) : arcPath(cx, cy, rr, a - sp / 2, a + sp / 2)
      out.push(`<path id="${pid}o${j}" d="${d}" fill="none"/><text class="sb-orb" text-anchor="middle"><textPath href="#${pid}o${j}" startOffset="50%" lang="to" data-row="${r.id}">${esc(r.to)}</textPath></text>`)
    })
    // the rim: a label per lesson (numbers on a phone)
    for (let i = 0; i < 52; i++) {
      const a = i * 360 / 52, [lx, ly] = pol(cx, cy, R + 11, a), left = a > 180
      out.push(`<text class="sb-rim" data-n="${i + 1}" x="${lx.toFixed(1)}" y="${ly.toFixed(1)}" text-anchor="${left ? 'end' : 'start'}" dominant-baseline="middle" transform="rotate(${(left ? a + 90 : a - 90).toFixed(1)} ${lx.toFixed(1)} ${ly.toFixed(1)})">${side ? `Lesson ${i + 1}` : i + 1}</text>`)
    }
    out.push(`</g>`)
    // medallion: the seed of life
    const m = side ? 14 : 9
    out.push(`<circle cx="${cx}" cy="${cy}" r="${m * 2.2}" fill="${BP}" stroke="${RING}"/>`)
    for (let i = 0; i < 7; i++) { const [x, y] = i ? pol(cx, cy, m, i * 60) : [cx, cy]; out.push(`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${m}" fill="none" stroke="${RING}" stroke-opacity=".9"/>`) }
    out.push(`</g>`)
    wheel.innerHTML = out.join('')
    wheelG = { scale: wheel.querySelector('.sb-wscale'), rot: wheel.querySelector('.sb-wrot') }
    rimEls = [...wheel.querySelectorAll('.sb-rim')]
    orbEls = [...wheel.querySelectorAll('.sb-orb')]
  }
  let wheelBuilds = 0
  function placeLabs() {
    labs.forEach(c => { c.style.left = c.style.top = '' })
    if (geo.side) {
      labs[0].style.left = '24px'; labs[0].style.top = Math.max(16, geo.wcy - 200) + 'px'
      labs[1].style.left = '24px'; labs[1].style.top = (geo.wcy + 20) + 'px'
    } else {
      const w0 = labs[0].offsetWidth
      labs[0].style.left = Math.max(4, (W - w0) / 2) + 'px'; labs[0].style.top = (geo.wcy + geo.R + geo.rimOut + 18) + 'px'
    }
  }

  // ---------- the sentence ----------
  function face(r, k, cls = '') {
    const w = r.words[k]
    const lab = w[1] ? `<span class="sb-lab" data-src="${esc(srcText(w[2]))}" title="${esc(srcText(w[2]))}">${esc(w[1])}</span>` : '<span class="sb-lab none">label</span>'
    return `<div class="sb-face ${cls}" data-row="${r.id}" data-i="${k}">${lab}<span class="sb-w" lang="to" data-row="${r.id}" data-i="${k}">${esc(w[0])}</span></div>`
  }
  const sizeCache = new Map()
  function faceSize(r, k) {
    const key = wcls + (W < 340 ? 't' : '') + r.id + ':' + k
    if (sizeCache.has(key)) return sizeCache.get(key)
    measure.className = 'sb-measure'
    measure.innerHTML = face(r, k)
    const f = measure.firstChild; f.style.position = 'static'; f.style.display = 'inline-grid'
    const s = { w: f.offsetWidth, h: f.offsetHeight }
    measure.innerHTML = ''
    sizeCache.set(key, s); return s
  }
  function textH(html, width, cls) {
    measure.innerHTML = `<div class="sb-en" style="position:static;width:${width}px"><p style="position:static" class="${cls || ''}">${html}</p></div>`
    const hgt = measure.firstChild.firstChild.offsetHeight; measure.innerHTML = ''; return hgt
  }
  // one width per slot across the spins, the turn and the describing word, so the sentence never jumps sideways there
  let groupW = null, groupH = 0
  function groupWidths() {
    const wv = [0, 0, 0]; groupH = 0
    for (const s of PLAY.segs) { if (s.rows.some(id => ROWS[id].words.length !== 3)) continue; for (const id of s.rows) for (let k = 0; k < 3; k++) { const z = faceSize(ROWS[id], k); wv[k] = Math.max(wv[k], z.w) } }
    // one tile height for the whole play, so no tile changes height between beats
    for (const s of PLAY.segs) for (const id of s.rows) ROWS[id].words.forEach((_, k) => { groupH = Math.max(groupH, faceSize(ROWS[id], k).h) })
    return wv
  }
  const segGroup = s => s.rows.every(id => ROWS[id].words.length === 3) && !(s.k === 'morph' && s.keys[1].length !== 3)

  // the widths each slot ends a segment with, derived from the timeline and the current width (never from what was drawn before)
  function endWidths(i) {
    const d = PLAY.segs[i], out = {}
    if (!d) return out
    if (d.k === 'drum') { for (let k = 0; k < ROWS[d.rows[0]].words.length; k++) out[['T', 'P', 'V'][k]] = groupW[k]; return out }
    const B = ROWS[d.rows[1]]
    d.keys[1].forEach((key, ib) => { out[key] = segGroup(d) ? groupW[ib] : faceSize(B, ib).w })
    return out
  }
  function buildSeg(i) {
    // this mount's own working copy of the segment: cells, measurements and layouts live here, not in the imported data
    seg = { ...PLAY.segs[i] }; segIdx = i
    const s = seg, gap = geo.narrow ? 8 : 10
    line.innerHTML = ''; enBox.innerHTML = ''
    const cells = []
    if (s.k === 'drum') {
      const R = s.rows.map(id => ROWS[id])
      for (let k = 0; k < R[0].words.length; k++) {
        const isDrum = s.cells.includes(k)
        const c = h('div', 'sb-cell' + (isDrum ? ' drum' : ''))
        c.innerHTML = R.map(r => face(r, k)).join('')
        c._faces = [...c.children]
        c._type = isDrum ? 'drum' : 'follow'
        c._learned = s.learned[k]
        const w = groupW[k], hh = groupH
        c._wA = c._wB = w; c._h = hh
        c._faces.forEach(f => { f.style.width = w + 'px'; f.style.height = hh + 'px' })
        cells.push(c)
      }
      s._en = R.map(r => r.en)
    } else {
      const A = ROWS[s.rows[0]], B = ROWS[s.rows[1]], [KA, KB] = s.keys
      const order = []
      KB.forEach(k => order.push(k))
      KA.forEach((k, i2) => { if (!KB.includes(k)) { const prev = KA[i2 - 1]; order.splice(prev ? order.indexOf(prev) + 1 : 0, 0, k) } })
      const prevW = endWidths(i - 1)
      for (const key of order) {
        const ia = KA.indexOf(key), ib = KB.indexOf(key)
        const c = h('div', 'sb-cell')
        let type
        if (ia >= 0 && ib >= 0) {
          const same = A.words[ia][0] === B.words[ib][0] && (A.words[ia][1] || '') === (B.words[ib][1] || '')
          type = same ? 'static' : 'roll'
          const pink = KA.length !== KB.length && s.learned[ib] === s.lesson ? 'new' : ''
          c.innerHTML = same ? face(B, ib).replace('data-row="' + B.id + '" data-i', `data-rows="${A.id} ${B.id}" data-row="${B.id}" data-i`) : face(A, ia) + face(B, ib, pink)
        } else if (ib >= 0) { type = 'grow'; c.innerHTML = face(B, ib, 'new') } else { type = 'shrink'; c.innerHTML = face(A, ia) }
        c._faces = [...c.children]; c._type = type; c._key = key
        const sa = ia >= 0 ? faceSize(A, ia) : { w: 0, h: 0 }, sb = ib >= 0 ? faceSize(B, ib) : { w: 0, h: 0 }
        c._wA = ia >= 0 ? (prevW[key] ?? sa.w) : 0
        c._wB = ib >= 0 ? (segGroup(s) ? groupW[ib] : sb.w) : 0
        c._h = groupH
        c._learned = ib >= 0 ? s.learned[ib] : (PLAY.segs[i - 1] ? PLAY.segs[i - 1].learned[ia] : s.learned[0])
        c._faces.forEach((f, j) => { const fw = c._faces.length === 2 ? (j === 0 ? sa.w : sb.w) : (type === 'shrink' ? sa.w : sb.w); f.style.width = Math.max(fw, 0) + 'px'; f.style.height = c._h + 'px' })
        cells.push(c)
      }
      s._en = [A.en, B.en]
    }
    cells.forEach(c => line.append(c))
    const punct = h('div', 'sb-punct', esc(ROWS[s.rows[0]].punct)); line.append(punct)
    seg._cells = cells; seg._punct = punct
    // the English ring
    const enW = W - 8
    seg._enH = Math.max(...s._en.map(e => textH(esc(e), enW)))
    enBox.innerHTML = s._en.map((e, j) => `<p data-row="${s.rows[j]}">${esc(e)}</p>`).join('')
    seg._ens = [...enBox.children]
    enBox.style.height = seg._enH + 'px'
    seg._ens.forEach(p => { p.style.width = enW + 'px' })
    // line layouts at the start and the end of the segment
    const tileH = Math.max(...cells.map(c => c._h))
    seg._tileH = tileH
    // a three-slot sentence always sits on one line, scaled down if the screen is too narrow for it
    const natural = ws => ws.reduce((a, w) => a + w, 0) + gap * (ws.filter(w => w > 0).length - 1) + 24
    const avail = W - 24
    seg._fitA = segGroup(s) || (s.k === 'morph' && cells.every(c => c._wA === 0 || c._type !== 'grow') && s.keys[0].length === 3) ? Math.min(1, avail / natural(cells.map(c => c._wA))) : 1
    seg._fitB = segGroup(s) ? Math.min(1, avail / natural(cells.map(c => c._wB))) : 1
    seg._rowsA = segGroup(s) || seg._fitA < 1 ? [cells.map((_, i) => i)] : rowsOf(cells.map(c => c._wA), gap, avail)
    seg._rowsB = segGroup(s) ? [cells.map((_, i) => i)] : rowsOf(cells.map(c => c._wB), gap, avail)
    seg._gap = gap
  }
  function rowsOf(ws, gap, avail) {
    const rows = [[]]; let x = 0
    ws.forEach((w, i) => { if (w > 0 && x > 0 && x + w > avail) { rows.push([]); x = 0 } rows[rows.length - 1].push(i); if (w > 0) x += w + gap })
    return rows
  }
  function place(ws, rows, gap, tileH, fit) {
    const pos = new Array(ws.length), rowGap = geo.narrow ? 12 : 16, ww = W / fit
    let end = null
    rows.forEach((r, ri) => {
      const g = r.map(i => gap * Math.min(1, ws[i] / 30))
      const tot = r.reduce((a, i, k) => a + ws[i] + (k < r.length - 1 ? g[k] : 0), 0)
      let xx = (ww - tot) / 2 - 8
      r.forEach((i, k) => { pos[i] = { x: xx, y: ri * (tileH + rowGap) }; xx += ws[i] + (k < r.length - 1 ? g[k] : 0) })
      if (ri === rows.length - 1) end = { x: xx + 4, y: ri * (tileH + rowGap) }
    })
    // scale about the centre of the stage
    const k = fit, cx = ww / 2
    pos.forEach(p => { p.x = W / 2 + (p.x - cx) * k; p.y *= k })
    end.x = W / 2 + (end.x - cx) * k; end.y *= k
    return { pos, h: (rows.length * tileH + (rows.length - 1) * rowGap) * k, punct: end }
  }
  function posAt(moves, tt) {
    let p = moves[0][2]
    for (const [t0, t1, p0, p1] of moves) { if (tt < t0) return p; if (tt < t1) return p0 + (p1 - p0) * E((tt - t0) / (t1 - t0)); p = p1 }
    return p
  }
  const wrapD = (d, n) => { d = ((d % n) + n) % n; return d > n / 2 ? d - n : d }
  function pulseAt(moves, tt) { for (const m of moves) { const d = tt - m[1]; if (d >= 0 && d < 0.24) return 1 + 0.07 * Math.sin(Math.PI * d / 0.24) } return 1 }

  function drumFaces(c, pos, v) {
    const n = c._faces.length, H = c._h, step = 34
    const R = H / 2 / Math.tan(step / 2 * Math.PI / 180), reach = 2.4
    const blur = v > 5 ? Math.min(1.3, (v - 5) * 0.13) : 0
    c._faces.forEach((f, i) => {
      const d = n === 2 ? i - pos : wrapD(i - pos, n), ad = Math.abs(d)
      f.style.transform = `translateZ(${-R}px) rotateX(${-d * step}deg) translateZ(${R}px)`
      if (ad > reach) { f.style.visibility = 'hidden'; f.style.opacity = 0; f.classList.remove('win'); f.classList.add('off'); f.lastChild.style.filter = ''; return }
      const op = clamp(1 - 0.38 * ad) * (ad > reach - 0.4 ? (reach - ad) / 0.4 : 1)
      f.style.opacity = op; f.style.visibility = op > 0.01 ? 'visible' : 'hidden'
      f.classList.toggle('off', ad >= 0.5); f.classList.toggle('win', ad < 0.5)
      const w = f.lastChild; w.style.filter = blur ? `blur(${blur.toFixed(2)}px)` : ''
    })
  }
  function showOnly(c, j) { c._faces.forEach((f, i) => { f.style.transform = ''; f.style.opacity = i === j ? 1 : 0; f.style.visibility = i === j ? 'visible' : 'hidden'; f.classList.toggle('win', i === j) }) }

  function renderSentence(tt) {
    let i = PLAY.segs.findIndex(s => tt >= s.t0 && tt < s.t1)
    if (i < 0) i = PLAY.segs.length - 1
    if (i !== segIdx) buildSeg(i) // a morph starts at the widths the previous segment ends with (endWidths)
    const s = seg, n = s.rows.length
    let pos, e, k = 1, v = 0
    if (s.k === 'drum') { pos = posAt(s.moves, tt); v = Math.abs(posAt(s.moves, tt + 0.02) - pos) / 0.02; k = pulseAt(s.moves, tt); e = 0 }
    else { e = E(span(s.s0, s.s1, tt)); pos = e; k = pulseAt([[s.s0, s.s1]], tt) }
    root.style.setProperty('--sbk', k.toFixed(3))
    const shown = ((Math.round(pos) % n) + n) % n
    const ee = s.k === 'morph' ? smooth(span(s.s0, s.s1, tt)) : 0
    const wsNow = s._cells.map(c => lerp(c._wA, c._wB, ee))
    const fit = lerp(s._fitA, s._fitB, ee)
    const LA = place(wsNow, s._rowsA, s._gap, s._tileH, fit), LB = place(wsNow, s._rowsB, s._gap, s._tileH, fit)
    s._fit = fit
    // vertical placement: the English sits above the tiles; a turning drum needs room for its neighbours
    const drumRoom = segGroup(s) || (s.k === 'morph' && s.rows[0] === 'ch03-l027-0') ? (geo.narrow ? 84 : 112) : 0
    const roomNow = s.rows[0] === 'ch03-l027-0' && s.k === 'morph' ? lerp(drumRoom, 0, ee) : (segGroup(s) ? drumRoom : 0)
    const enGap = (geo.narrow ? 18 : 22) + roomNow
    const blockH = lerp(LA.h, LB.h, ee)
    const area = geo.playH - geo.roadH - 30
    const totalH = s._enH + enGap + blockH
    const y0 = Math.max(roomNow * 0.25, (area - totalH) / 2 + (geo.narrow ? 0 : 6))
    enBox.style.transform = `translateY(${y0}px)`
    line.style.top = (y0 + s._enH + enGap) + 'px'
    s._lineTop = y0 + s._enH + enGap
    s._cells.forEach((c, ci) => {
      const a = LA.pos[ci], b = LB.pos[ci]
      const x = lerp(a.x, b.x, ee), y = lerp(a.y, b.y, ee)
      const w = wsNow[ci]
      c.style.transform = `translate(${x.toFixed(1)}px,${y.toFixed(1)}px) scale(${fit.toFixed(4)})`
      c.style.transformOrigin = '0 0'
      c.style.width = w + 'px'; c.style.height = c._h + 'px'
      c._x = x; c._y = y; c._w = w * fit; c._hs = c._h * fit
      if (c._type === 'drum') drumFaces(c, pos, v)
      else if (c._type === 'follow') showOnly(c, shown)
      else if (c._type === 'roll') {
        drumFaces(c, pos, v)
        const moving = tt >= s.s0 && tt < s.s1 + 0.24
        c.classList.toggle('drum', moving)
        const mid = 1 - Math.abs(2 * ee - 1)
        c._faces.forEach(f => { f.style.left = (w - parseFloat(f.style.width)) / 2 + 'px'; if (!f.classList.contains('win')) { const o = +f.style.opacity * mid; f.style.opacity = o; f.style.visibility = o > 0.01 ? 'visible' : 'hidden' } })
      }
      else if (c._type === 'static') showOnly(c, 0)
      // an arriving (or leaving) word unfolds with its slot rather than being cut by the slot's edge: no painted text is ever clipped
      else if (c._type === 'grow') { const op = clamp((e - 0.5) * 2.5); const f = c._faces[0], sx = clamp(w / (parseFloat(f.style.width) || 1), 0.001, 1); f.style.opacity = op; f.style.visibility = e >= 0.5 ? 'visible' : 'hidden'; f.style.transformOrigin = '0 0'; f.style.transform = `translateY(${((1 - op) * -14).toFixed(1)}px) scaleX(${sx.toFixed(4)})`; f.style.left = '0px' }
      else if (c._type === 'shrink') { const op = 1 - clamp(e * 2.5); const f = c._faces[0], sx = clamp(w / (parseFloat(f.style.width) || 1), 0.001, 1); f.style.opacity = op; f.style.visibility = e < 0.5 && op > 0.01 ? 'visible' : 'hidden'; f.style.transformOrigin = '0 0'; f.style.transform = `scaleX(${sx.toFixed(4)})`; f.style.left = '0px' }
      c._live = c._type !== 'shrink' ? (c._type !== 'grow' || e >= 0.5) : e < 0.5
    })
    const pA = LA.punct, pB = LB.punct
    s._punct.style.transform = `translate(${lerp(pA.x, pB.x, ee).toFixed(1)}px,${(lerp(pA.y, pB.y, ee) + (s._tileH - (geo.narrow ? 34 : 56)) * fit).toFixed(1)}px) scale(${fit.toFixed(4)})`
    s._punct.style.transformOrigin = '0 0'
    // the English rolls in step with the slot
    const H = s._enH
    s._ens.forEach((p, j) => {
      const d = n === 2 && s.k === 'morph' ? j - pos : wrapD(j - pos, n), ad = Math.abs(d)
      const op = clamp(1 - ad * 1.1)
      p.style.opacity = op; p.style.visibility = op > 0.01 ? 'visible' : 'hidden'
      p.style.transform = `translateY(${(d * H * 0.8).toFixed(1)}px)`
      p.classList.toggle('settled', ad < 0.02)
    })
    s._shown = shown
    // "Then on to Lesson 52."
    const mo = s.more ? clamp((tt - s.more) / 0.3) : 0
    more.style.opacity = mo; more.style.visibility = mo > 0 ? 'visible' : 'hidden'
    more.style.top = (geo.playH - geo.roadH - (geo.narrow ? 30 : 36)) + 'px'
    return s
  }

  // ---------- lesson flag, road and links ----------
  function lessonAt(tt) {
    if (tt >= PLAY.page) return 9
    const s = PLAY.segs.find(x => tt >= x.t0 && tt < x.t1) || PLAY.segs[PLAY.segs.length - 1]
    return s.lesson
  }
  let flagN = -1
  function renderRoad(n) {
    if (n !== flagN) {
      flag.querySelector('.n').textContent = n
      road.querySelectorAll('.sb-stop').forEach(st => { const k = +st.dataset.n; st.classList.toggle('done', k <= n && k !== 52); st.classList.toggle('now', k === n); const b = st.querySelector('b.opt'); if (b) b.style.visibility = k === n ? 'visible' : 'hidden' })
      flagN = n; stopX = null
    }
  }
  let stopX = null
  function stopCenters() {
    if (stopX) return stopX
    const box = stage.getBoundingClientRect()
    stopX = {}
    road.querySelectorAll('.sb-stop').forEach(st => { const r = st.querySelector('i').getBoundingClientRect(); stopX[st.dataset.n] = { x: r.left + r.width / 2 - box.left, y: r.top - box.top - 2 } })
    return stopX
  }
  function drawLinks(s, n, op) {
    if (op <= 0 || !s) { svg.innerHTML = ''; return }
    const sc = stopCenters(); let p = ''
    for (const [ci, c] of s._cells.entries()) {
      if (!c._live || c._w < 2) continue
      if (geo.narrow && c._learned !== n) continue
      const st = sc[c._learned]; if (!st) continue
      const x1 = c._x + c._w / 2, y1 = s._lineTop + c._y + c._hs + (c.classList.contains('drum') ? 8 : 2)
      const my = (y1 + st.y) / 2
      c.dataset.ci = ci
      p += `<path data-ci="${ci}" d="M${x1.toFixed(1)} ${y1.toFixed(1)} C ${x1.toFixed(1)} ${my.toFixed(1)}, ${st.x.toFixed(1)} ${my.toFixed(1)}, ${st.x.toFixed(1)} ${st.y.toFixed(1)}"/>`
    }
    svg.innerHTML = p; svg.style.opacity = op
  }

  // ---------- the ending: card stack, deal, carousel, curve ----------
  const panC = tt => geo.C0 + (geo.C1 - geo.C0) * smoother(span(BEAT['pan-early'].start, BEAT['pan-late'].end, tt))
  function counterLesson(tt) {
    if (tt < PAGE) return lessonAt(tt)
    if (tt < BEAT.deal.start) return 9
    if (tt < BEAT['pan-early'].start) return 1
    return clamp(Math.round(panC(tt)), 1, 52)
  }
  // a card paints only while its whole box is inside the stage, so no card is ever cut by the stage's edge
  function edgeOp(x, y, s, rotDeg, H) {
    const a = rotDeg * Math.PI / 180, cw = geo.cw * s / 2, ch = geo.ch * s / 2
    const hx = Math.abs(Math.cos(a)) * cw + Math.abs(Math.sin(a)) * ch, hy = Math.abs(Math.sin(a)) * cw + Math.abs(Math.cos(a)) * ch
    return clamp((Math.min(x - hx, W - x - hx, y - hy, H - y - hy) - 3) / geo.band)
  }
  let cardsShown = false
  function renderCards(tt, H) {
    const on = tt >= PAGE && tt < BEAT.curve.end
    if (!on) { if (cardsShown) { cards.forEach(c => { c.style.visibility = 'hidden'; c.style.opacity = 0 }); cardsShown = false } return }
    cardsShown = true
    const cx0 = W / 2, cy0 = geo.rowCy, R = geo.R
    const bpOn = tt >= BEAT.curve.start + 0.25
    let curN = 0
    if (tt < BEAT.deal.start) curN = 9
    else if (tt >= BEAT['pan-early'].start && tt < BEAT.curve.start) curN = Math.round(panC(tt))
    else if (tt >= dealStart(1) + 0.26 && tt < BEAT.curve.start) curN = Math.round(geo.C0)
    // the curve: the row bends down into a ring, Lesson 50 (the carousel's last frame) on top, Lesson 52 meeting Lesson 1
    const u = smooth(span(BEAT.curve.start, BEAT.curve.end, tt))
    const spRing = 2 * Math.PI * R / 52, spU = Math.exp(lerp(Math.log(geo.sp), Math.log(spRing), u)), k = u / R
    const P = { x: lerp(cx0, geo.wcx, smooth(u)), y: lerp(cy0, geo.wcy - R, smooth(u)) }
    cards.forEach((c, i) => {
      const n = i + 1
      let x, y, s = 1, rot = 0, op = 1, z = 1
      if (tt < BEAT.deal.start) {
        // the Lesson 9 page holds, then shrinks onto the stack; the stack fades in under it
        if (n === 9) { const sh = smooth(span(PAGE + 0.45, BEAT.stack.end - 0.05, tt)); s = lerp(geo.sPage, 1, sh); x = cx0; y = cy0; op = smooth(span(PAGE + 0.05, PAGE + 0.45, tt)); z = 60 }
        else { const d = stackDepth(n); x = cx0 + 5 * d; y = cy0 - 5 * d; op = smooth(span(PAGE + 0.45, PAGE + 0.75, tt)); z = 50 - d }
      } else if (tt < BEAT['pan-early'].start) {
        // the deal: from the bottom, Lesson 1 first, each card lifting off the stack into its place in the row
        const st = dealStart(n), e = E(span(st, st + 0.26, tt)), d = stackDepth(n)
        const ax = cx0 + 5 * d, ay = cy0 - 5 * d, bx = cx0 + (n - geo.C0) * geo.sp
        x = lerp(ax, bx, e); y = lerp(ay, cy0, e) - 34 * Math.sin(Math.PI * e)
        z = e > 0 ? 80 - n : n === 9 ? 60 : 50 - d
      } else if (tt < BEAT.curve.start) {
        x = cx0 + (n - panC(tt)) * geo.sp; y = cy0
      } else {
        const sN = (((n - geo.C1) % 52 + 78) % 52 - 26) * spU, th = k * sN
        x = P.x + (k > 1e-6 ? Math.sin(th) / k : sN); y = P.y + (k > 1e-6 ? (1 - Math.cos(th)) / k : 0)
        rot = th * 180 / Math.PI; s = Math.exp(lerp(0, Math.log(0.2), u)); op = 1 - smooth(span(0.55, 0.95, u))
      }
      op *= edgeOp(x, y, s, rot, H)
      c.style.transform = `translate(${(x - geo.cw / 2).toFixed(1)}px,${(y - geo.ch / 2).toFixed(1)}px) rotate(${rot.toFixed(2)}deg) scale(${s.toFixed(4)})`
      c.style.opacity = op.toFixed(3); c.style.visibility = op > 0.003 ? 'visible' : 'hidden'; c.style.zIndex = z
      c.classList.toggle('cur', n === curN); c.classList.toggle('bp', bpOn)
    })
  }

  // ---------- the wheel turns, counter-spins and unfolds ----------
  const rotAt = tt => { const r0 = geo.rot0; return tt < BEAT.wheel.start ? r0 : tt < BEAT.counter.start ? r0 + ROT_TURN * span(BEAT.wheel.start, BEAT.wheel.end, tt) : r0 + ROT_TURN - ROT_BACK * smooth(span(BEAT.counter.start, BEAT.counter.end, tt)) }
  const scaleAt = tt => lerp(1, 0.6, smooth(span(BEAT.counter.start, BEAT.counter.start + 0.9, tt)))
  function rimPos(n, tt) { const [x, y] = pol(geo.wcx, geo.wcy, geo.R * scaleAt(tt), rotAt(tt) + (n - 1) * 360 / 52); return { x, y } }
  let wheelShown = false
  function renderWheel(tt) {
    const cv = BEAT.curve, appear = smooth(span(cv.start + 0.6 * (cv.end - cv.start), cv.end, tt))
    const op = appear * (1 - smooth(span(BEAT.counter.end - 0.35, BEAT.counter.end, tt)))
    const on = op > 0.003 && tt < BEAT.counter.end
    if (!on) { if (wheelShown) { wheel.style.visibility = 'hidden'; wheel.style.opacity = 0; labs.forEach(l => { l.style.visibility = 'hidden'; l.style.opacity = 0 }); wheelShown = false } return }
    wheelShown = true
    wheel.style.visibility = 'visible'; wheel.style.opacity = op.toFixed(3)
    const cx = geo.wcx, cy = geo.wcy, s = scaleAt(tt), a = rotAt(tt)
    wheelG.scale.setAttribute('transform', `translate(${cx} ${cy}) scale(${s.toFixed(4)}) translate(${-cx} ${-cy})`)
    wheelG.rot.setAttribute('transform', `rotate(${a.toFixed(2)} ${cx} ${cy})`)
    const orb = smooth(span(BEAT.wheel.start, BEAT.wheel.start + 0.35, tt)) * (1 - smooth(span(BEAT.counter.start, BEAT.counter.start + 0.35, tt)))
    orbEls.forEach(o => { o.style.opacity = orb.toFixed(3); o.style.visibility = orb > 0.003 ? 'visible' : 'hidden' })
    rimEls.forEach((r, i) => { const t0 = chipStart(i + 1), o = 1 - clamp((tt - t0) / 0.12); r.style.opacity = o.toFixed(3); r.style.visibility = o > 0.003 ? 'visible' : 'hidden' })
    labs.forEach((l, i) => { const o = i === 0 || geo.side ? orb : 0; l.style.opacity = o.toFixed(3); l.style.visibility = o > 0.003 ? 'visible' : 'hidden' })
  }
  function renderCourse(tt) {
    if (tt < BEAT.counter.start) { course.style.visibility = 'hidden'; course.style.opacity = 0; return }
    course.style.visibility = 'visible'; course.style.opacity = 1
    const rest = smooth(span(BEAT.course.start - 0.15, BEAT.course.end - 0.1, tt))
    const off = geo.courseOff
    chips.forEach((b, i) => {
      const n = i + 1, t0 = chipStart(n), e = E(span(t0, t0 + CHIP_FLY, tt)), ch = b.firstChild, to = chipPos[i]
      const ttl = b.children[1]; if (ttl) { ttl.style.opacity = rest.toFixed(3); ttl.style.visibility = rest > 0.003 ? 'visible' : 'hidden' }
      if (tt < t0) { ch.style.visibility = 'hidden'; ch.style.opacity = 0; ch.style.transform = ''; return }
      const from = rimPos(n, t0), dx = (from.x - off.x - to.x) * (1 - e), dy = (from.y - off.y - to.y) * (1 - e) - 40 * Math.sin(Math.PI * e)
      ch.style.transform = e >= 1 ? '' : `translate(${dx.toFixed(1)}px,${dy.toFixed(1)}px)`
      const o = clamp((tt - t0) / 0.08); ch.style.opacity = o.toFixed(3); ch.style.visibility = o > 0.003 ? 'visible' : 'hidden'
    })
    for (const e of course.querySelectorAll('.sb-gname, .sb-hintc')) { e.style.opacity = rest.toFixed(3); e.style.visibility = rest > 0.003 ? 'visible' : 'hidden' }
    const ro = smooth(span(BEAT.counter.start + 0.5, BEAT.course.start + 0.3, tt))
    course._road.style.opacity = ro.toFixed(3); course._road.style.visibility = ro > 0.003 ? 'visible' : 'hidden'
  }
  function courseAtRest() {
    course.style.visibility = 'visible'; course.style.opacity = 1
    chips.forEach(b => { const ch = b.firstChild; ch.style.transform = ''; ch.style.opacity = 1; ch.style.visibility = 'visible'; const ttl = b.children[1]; if (ttl) { ttl.style.opacity = 1; ttl.style.visibility = 'visible' } })
    for (const e of course.querySelectorAll('.sb-gname, .sb-hintc')) { e.style.opacity = 1; e.style.visibility = 'visible' }
    course._road.style.opacity = 1; course._road.style.visibility = 'visible'
  }

  // ---------- the preview card ----------
  function pvHtml(n) {
    const L = LESSONS[n - 1]
    let s = `<button type="button" class="sb-close" aria-label="Close">×</button>`
    s += `<h3 class="sb-pv-h" id="${pvId}" tabindex="-1"><span class="sb-pv-e"><span class="sb-pv-k">Lesson ${n}</span><span class="sb-pv-g" data-group="${L.group}">${esc(GROUP[L.group])}</span></span><span class="sb-pv-t">${esc(L.title)}</span></h3>`
    s += `<p class="sb-pv-sec">What this lesson teaches</p><ul class="sb-pv-topics">${L.topics.map(x => `<li>${mixedHtml(x)}</li>`).join('')}</ul>`
    s += `<p class="sb-pv-by">By the end of it you will be able to make sentences such as</p>`
    s += L.preview.map(id => { const r = ROWS[id]; return `<p class="sb-pv-ex"><span lang="to" data-row="${r.id}">${esc(r.to)}</span><span class="e" data-row="${r.id}">${esc(r.en)}</span></p>` }).join('')
    s += `<div class="sb-nav"><button type="button" class="sb-btn" data-go="-1"${n === 1 ? ' hidden' : ''}>← Lesson ${n - 1}</button><a class="sb-start" href="${esc(opt.lessonHref(n))}" data-lesson-link="${n}">Start Lesson ${n}</a><button type="button" class="sb-btn" data-go="1"${n === 52 ? ' hidden' : ''}>Lesson ${n + 1} →</button></div>`
    s += `<p class="sb-keys">Use ← and → to move between lessons.</p>`
    return s
  }
  function renderPv(announce) {
    if (!pvOpen) {
      pv.hidden = true
      if (pv.parentNode !== root) root.insertBefore(pv, live)
      chips.forEach(b => b.setAttribute('aria-expanded', 'false'))
      root.classList.remove('has-pv', 'is-docked')
      return
    }
    const L = LESSONS[selected - 1]
    pv.innerHTML = pvHtml(selected)
    pv.hidden = false
    chips.forEach(b => b.setAttribute('aria-expanded', +b.dataset.n === selected ? 'true' : 'false'))
    root.classList.add('has-pv')
    if (announce) live.textContent = `Lesson ${L.n}: ${L.title}. ${L.topics.length} topics and ${L.preview.length} example sentences.`
    placePv()
  }
  function placePv() {
    if (!pvOpen) return
    if (!geo.courseWide) {
      // a sheet under the chosen lesson's row, so the lesson, its row and the card are seen together
      root.classList.remove('is-docked')
      pv.style.left = pv.style.right = pv.style.top = ''
      const row = chips[selected - 1].parentNode
      if (pv.previousSibling !== row || pv.parentNode !== row.parentNode) row.after(pv)
      return
    }
    root.classList.add('is-docked')
    if (pv.parentNode !== root) root.insertBefore(pv, live)
    // docked on the side away from the lesson, so the lesson and its focus ring are never under the card
    const x = chipPos[selected - 1].x + geo.courseOff.x
    const right = x < W / 2
    const pad = parseFloat(getComputedStyle(panel).paddingRight) || 0
    pv.style.top = (panel.offsetTop + stage.offsetTop + 8) + 'px'
    pv.style.left = right ? '' : pad + 'px'
    pv.style.right = right ? pad + 'px' : ''
  }
  function revealPv() {
    // the card is on screen: scroll the least needed to show it (its top first if it is taller than the screen)
    const r = pv.getBoundingClientRect(), vh = window.innerHeight || 800
    if (r.top < 0 || r.bottom > vh) {
      const dy = r.height > vh - 16 ? r.top - 8 : (r.top < 0 ? r.top - 8 : r.bottom - vh + 8)
      window.scrollBy({ top: dy, behavior: 'instant' })
    }
  }
  function select(n, how = {}) {
    n = clamp(n, 1, 52)
    if (mode !== 'end') finish(false)
    selected = n; pvOpen = true
    renderPv(how.announce !== false)
    if (how.focusChip) chips[n - 1].focus({ preventScroll: true })
    if (how.focusPv) pv.querySelector('.sb-pv-h').focus({ preventScroll: true })
    if (how.reveal !== false) revealPv()
  }
  function closePv(focusChip = true) {
    pvOpen = false
    renderPv(false)
    if (focusChip && selected) { chips[selected - 1].focus({ preventScroll: true }); const r = chips[selected - 1].getBoundingClientRect(); if (r.top < 0 || r.bottom > innerHeight) chips[selected - 1].scrollIntoView({ block: 'center' }) }
  }

  // ---------- frame ----------
  function renderEndLayout() {
    root.classList.add('is-end', 'is-dark')
    ground.style.opacity = 1
    flag.hidden = true; bphead.hidden = true; chead.hidden = false; chead.style.opacity = 1
    // opacity as well as visibility: a drum face caught mid-spin keeps its own visibility:visible, which a hidden parent cannot override
    sent.style.visibility = 'hidden'; sent.style.opacity = 0; svg.innerHTML = ''; road.style.visibility = 'hidden'; road.style.opacity = 0
    renderCards(END + 1, geo.H); renderWheel(END + 1)
    stage.style.height = geo.courseWide ? geo.H + 'px' : ''
    courseAtRest()
    bPause.hidden = true; bSkip.hidden = true; bReplay.hidden = false
    renderPv(false)
  }
  function render(tt) {
    if (destroyed) return
    t = clamp(tt, 0, END)
    if (mode === 'end') { renderEndLayout(); return }
    root.classList.remove('is-end')
    const g = geo
    renderRoad(counterLesson(t))
    // chrome: white through the carousel, blueprint blue from the curve on
    ground.style.opacity = smooth(span(BEAT.curve.start, BEAT.curve.start + 0.42, t))
    root.classList.toggle('is-dark', t >= BEAT.curve.start + 0.25)
    flag.hidden = t >= BEAT.curve.start + 0.25
    bphead.hidden = !(t >= BEAT.curve.start + 0.25 && t < BEAT.course.start)
    bphead.style.opacity = clamp((t - BEAT.curve.start - 0.25) / 0.35)
    chead.hidden = !(t >= BEAT.course.start)
    chead.style.opacity = clamp((t - BEAT.course.start) / 0.3)
    bPause.hidden = false; bSkip.hidden = false; bReplay.hidden = false
    // stage height: one height on desktop; a phone grows to the course view as the wheel unfolds
    const H = g.courseWide ? g.H : lerp(g.playH, Math.max(g.playH, g.courseH), smooth(span(BEAT.counter.start, BEAT.counter.start + 0.4, t)))
    stage.style.height = H + 'px'
    // the sentence
    if (t < PAGE + 0.5) {
      sent.style.visibility = 'visible'
      const s = renderSentence(Math.min(t, PAGE - 1e-3))
      const so = 1 - smooth(span(PAGE, PAGE + 0.4, t))
      sent.style.opacity = so
      drawLinks(s, lessonAt(Math.min(t, PAGE - 1e-3)), so)
      road.style.visibility = 'visible'; road.style.opacity = so
    } else { sent.style.visibility = 'hidden'; sent.style.opacity = 0; svg.innerHTML = ''; road.style.visibility = 'hidden'; road.style.opacity = 0 }
    renderCards(t, H)
    renderWheel(t)
    renderCourse(t)
    pv.hidden = true
  }

  // ---------- clock ----------
  function tick(now) {
    raf = 0
    if (!playing || destroyed) return
    const dt = Math.min(0.1, (now - last) / 1000); last = now
    t += dt
    if (t >= END) { finish(false); return }
    render(t)
    rafReq(tick)
  }
  function play() {
    if (mode === 'end' || playing || destroyed) return
    playing = true; userPaused = false; autoPaused = false
    bPause.textContent = 'Pause'
    last = performance.now(); rafReq(tick)
  }
  function pause(byUser, auto) {
    if (byUser) userPaused = true
    if (auto && playing) autoPaused = true
    playing = false; if (raf) { cancelAnimationFrame(raf); raf = 0 }
    bPause.textContent = 'Play'
  }
  function finish() {
    pause(false); mode = 'end'; t = END
    render(END)
  }
  function replay() {
    pvOpen = false; renderPv(false)
    mode = 'play'; t = 0; segIdx = -1; flagN = -1
    root.classList.remove('is-end', 'is-dark')
    render(0); play()
  }

  // ---------- events ----------
  const on = (target, type, fn, o) => { target.addEventListener(type, fn, o); cleanups.push(() => target.removeEventListener(type, fn, o)) }
  const cleanups = []
  on(bPause, 'click', () => { if (playing) pause(true); else play() })
  on(bReplay, 'click', () => replay())
  on(bSkip, 'click', () => { finish(); bReplay.focus({ preventScroll: true }) })
  on(course, 'click', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    const n = +b.dataset.n
    if (pvOpen && n === selected && mode === 'end') { closePv(true); return }
    select(n, { announce: true })
  })
  on(course, 'focusin', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    if (mode !== 'end') finish()
    // while the card is open, the focused lesson becomes the open one, so the card docks away from it and never covers it;
    // with the card closed (Escape, ×) focus moves through the course without opening it
    if (pvOpen && +b.dataset.n !== selected) select(+b.dataset.n, { announce: false, reveal: false })
  })
  function rowStep(n, d) {
    const rows = geo.rowsOf, ri = rows.findIndex(r => r.includes(n)), to = rows[ri + d]
    if (!to) return null
    const x = chipPos[n - 1].x
    return to.reduce((best, m) => Math.abs(chipPos[m - 1].x - x) < Math.abs(chipPos[best - 1].x - x) ? m : best, to[0])
  }
  on(course, 'keydown', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    // a click or tap opens the card but leaves focus on the lesson, so Escape must close it from here too
    if (ev.key === 'Escape' && pvOpen) { ev.preventDefault(); closePv(true); return }
    const n = +b.dataset.n
    const go ={ ArrowLeft: n - 1, ArrowRight: n + 1, ArrowUp: rowStep(n, -1), ArrowDown: rowStep(n, 1), Home: 1, End: 52 }[ev.key]
    if (ev.key in { ArrowLeft: 1, ArrowRight: 1, ArrowUp: 1, ArrowDown: 1, Home: 1, End: 1 }) {
      ev.preventDefault()
      if (go != null && go >= 1 && go <= 52) { if (pvOpen) select(go, { focusChip: true, reveal: false }); else chips[go - 1].focus({ preventScroll: true }); const r = chips[go - 1].getBoundingClientRect(); if (r.top < 0 || r.bottom > innerHeight) chips[go - 1].scrollIntoView({ block: 'center' }) }
      return
    }
    if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); select(n, { focusPv: true, announce: true }) }
  })
  on(pv, 'click', ev => {
    const b = ev.target.closest('button, a'); if (!b) return
    if (b.classList.contains('sb-close')) { closePv(true); return }
    if (b.dataset.go) { const d = b.dataset.go; select(selected + +d, { announce: true }); const nb = pv.querySelector(`[data-go="${d}"]`); (nb && !nb.hidden ? nb : pv.querySelector('.sb-pv-h')).focus({ preventScroll: true }); return }
    if (b.dataset.lessonLink && opt.onNavigate && !(ev.metaKey || ev.ctrlKey || ev.shiftKey || ev.altKey)) { ev.preventDefault(); opt.onNavigate(b.getAttribute('href'), ev) }
  })
  // Shift+Tab out of the card onto a lesson before it closes the card (a click on a lesson is left to the click handler)
  let lastPointer = -1e9
  on(root, 'pointerdown', () => { lastPointer = performance.now() }, true)
  on(pv, 'focusout', ev => {
    const to = ev.relatedTarget
    if (!pvOpen || !to || pv.contains(to) || !to.closest || !to.closest('.sb-ls') || !root.contains(to) || performance.now() - lastPointer < 500) return
    if (to.compareDocumentPosition(pv) & Node.DOCUMENT_POSITION_FOLLOWING) closePv(false)
  })
  // 3: Escape closes an open card wherever focus is in the module, or with focus nowhere (Safari leaves it there after a click)
  on(document, 'keydown', ev => {
    if (ev.key !== 'Escape' || !pvOpen || ev.defaultPrevented) return
    const a = document.activeElement
    if (a && a !== document.body && a !== document.documentElement && !root.contains(a)) return
    ev.preventDefault(); closePv(true)
  })
  on(pv, 'keydown', ev => {
    if (ev.key === 'Escape') { ev.preventDefault(); closePv(true); return }
    if (ev.key === 'ArrowLeft' || ev.key === 'ArrowRight') {
      ev.preventDefault(); const d = ev.key === 'ArrowLeft' ? -1 : 1
      if (selected + d >= 1 && selected + d <= 52) select(selected + d, { focusPv: true, announce: true })
    }
  })
  // start when the section is mostly in view; pause when it leaves
  let io = null
  if (!reduced && typeof IntersectionObserver === 'function') {
    io = new IntersectionObserver(entries => {
      for (const en of entries) {
        const vh = window.innerHeight || 1
        const mostly = en.intersectionRatio >= opt.startRatio || en.intersectionRect.height >= vh * 0.6
        inView = mostly || (inView && en.intersectionRatio >= 0.2)
        if (mostly && mode === 'play' && !playing && !userPaused && !document.hidden) play()
        else if (en.intersectionRatio < 0.2 && playing) pause(false, true)
      }
    }, { threshold: [0, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1] })
    io.observe(panel)
  }
  // a hidden tab pauses; coming back resumes only a pause the module made itself, with the panel still in view and no Pause pressed
  on(document, 'visibilitychange', () => {
    if (document.hidden) { if (playing) pause(false, true) }
    else if (autoPaused && inView && !userPaused && mode === 'play' && !playing) play()
  })
  let ro = null
  const relayout = () => { if (destroyed) return; const w = stage.clientWidth; if (Math.abs(w - W) < 1 && geo) return; sizeCache.clear(); classify(); groupW = groupWidths(); segIdx = -1; stopX = null; flagN = -1; render(t) }
  if (typeof ResizeObserver === 'function') { ro = new ResizeObserver(() => relayout()); ro.observe(root) }

  // ---------- start ----------
  classify(); groupW = groupWidths()
  if (mode === 'end') { finish() } else render(0)
  if (document.fonts && document.fonts.status !== 'loaded') document.fonts.ready.then(() => { if (!destroyed) { sizeCache.clear(); courseKey = ''; classify(); groupW = groupWidths(); segIdx = -1; stopX = null; flagN = -1; render(t) } })

  const controller = {
    el, root,
    get time() { return t }, get mode() { return mode }, get playing() { return playing }, get selected() { return pvOpen ? selected : 0 }, get reduced() { return reduced },
    get cardOpen() { return pvOpen }, get timeline() { return TIMELINE },
    get geometry() { return { ...geo, width: W } },
    seek(tt, o = {}) { if (mode === 'end') { mode = 'play'; pvOpen = false; renderPv(false); root.classList.remove('is-end', 'is-dark') } pause(false); segIdx = -1; flagN = -1; render(tt); if (o.asPlaying) bPause.textContent = 'Pause'; return t },
    play, pause: () => pause(true), replay, skip: () => finish(), select: n => select(n, { announce: true }), close: () => closePv(false),
    destroy() {
      if (destroyed) return
      destroyed = true; pause(false)
      cleanups.forEach(f => f()); if (io) io.disconnect(); if (ro) ro.disconnect()
      root.remove(); instances.delete(controller)
      if (--styleRefs <= 0 && styleEl) { styleEl.remove(); styleEl = null; styleRefs = 0 }
    },
  }
  instances.add(controller)
  return controller
}

export function unmount(el) {
  for (const inst of [...instances]) if (!el || inst.el === el) inst.destroy()
}

export const data = DATA
export default { mount, unmount, TIMELINE }
