// Ported from reviews/sentence-bloom-web-2026-10-07/preview/sentence-bloom.js (Lea-Faka-Tonga working tree, approved at Step 6, 2026-10-08).
// Checked against: the site's book and lesson list at the lea-faka-tonga-app commit named in the header of src/data/sentence-bloom-data.js
// (generated by reviews/bloom-middle-2026-10-09/tools/build-data.mjs in the Lea-Faka-Tonga working tree, never edited by hand).
// Changes in the port, and only these: the data import path; okinafy imported from the site (src/lib/okinafy.js) instead of a copy;
// the module's two literal colours (dark grey text and the road-stop ring) replaced by the site's --wr-ink and --line-strong;
// two unused variables removed for lint; a modified click on Start Lesson N (new tab, new window) is left to the browser instead of onNavigate; the separator in the data's `sources` strings is ' | ' instead of an em dash (see the data file's port note), and the regex that reads it follows; the English line is moved with a transform instead of `top`, so its jumps between lines of the sentence are not layout shifts (Core Web Vitals) on the live page.
// The middle redone, 2026-10-09 (plans/2026-10-09-bloom-middle-pacing.md Step 5): reviews/bloom-middle-2026-10-09/Storyboard-Final.json,
// direction A as Andrew approved it. The stack, deal, carousel, curve and wheel of 2026-10-08 are gone; "the middle" below says what replaced them.
// Sentence bloom for the homepage: a 29.58 s play that ends on the whole course, explorable lesson by lesson.
// 0 to 15.88 s: one sentence spins, turns and grows (Storyboard.json). From 15.88 s the Lesson 9 page holds, then the camera pulls back
// until the page is chip 9 on the course's own road; chips 8, 9 and 10 hold with their titles; the camera widens to the course view's
// framing; a red stroke walks the road from 9 to 52, holding at the part openers 15, 21, 31 and 41; the road turns blueprint blue in
// place and is the course view (the site's six named parts).
// Self-contained ES module, no dependencies. mount(element, options) returns a controller; unmount() removes it.
// Look: the homepage's own tokens (--wr-*, --f-*, base.css); the blueprint keeps its ruled palette (#0d375c, #c4deff, #deecff).
// Every Tongan string comes from ./sentence-bloom-data.js (book rows found pair-level in both books, atlas-grammar labels
// with sources); lesson titles, topics and parts come from the site's chapters.json, verbatim (see the data file's header).
import DATA from '@app/data/sentence-bloom-data.js'
import { okinafy } from '@app/lib/okinafy.js'

// Development only: freeze the imported data, so any write into it throws instead of leaking state between mounts.
const DEV = (() => { try { if (import.meta.env) return !!import.meta.env.DEV } catch { /* not bundled */ } return typeof location !== 'undefined' && /^(localhost|127\.0\.0\.1)$/.test(location.hostname) })()
const deepFreeze = o => { if (o && typeof o === 'object' && !Object.isFrozen(o)) { Object.freeze(o); for (const v of Object.values(o)) deepFreeze(v) } return o }
if (DEV) deepFreeze(DATA)

const ROWS = DATA.rows, LESSONS = DATA.lessons, PLAY = DATA.play, COURSE = DATA.course
const PAGE = PLAY.page
const BP = '#0d375c', RING = '#c4deff', BPINK = '#deecff'
const clamp = (x, a = 0, b = 1) => Math.max(a, Math.min(b, x))
const lerp = (a, b, e) => a + (b - a) * e
const E = u => 1 - Math.pow(1 - clamp(u), 2.4)
const smooth = u => { u = clamp(u); return u * u * (3 - 2 * u) }
const span = (a, b, t) => clamp((t - a) / (b - a))
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])
const h = (tag, cls, html) => { const e = document.createElement(tag); if (cls) e.className = cls; if (html != null) e.innerHTML = html; return e }
const srcText = i => (i == null ? '' : okinafy(DATA.sources[i].replace(/^book\/Chapter-0?(\d+)\.md:[\d,-]+ \| /, 'Lesson $1: ')))
// The site's display rule for the glottal stop (src/lib/okinafy.js) is imported above: the data stays verbatim from chapters.json
// (ASCII apostrophe, DECISIONS.md 2026-06-20) and display turns an apostrophe before a vowel into the fakauʻa ʻ (U+02BB).
// Lesson titles are not passed through it: the site prints c.title raw (Lessons.jsx, Lesson.jsx), so the card prints it raw too.
// Topics: Tongan words marked lang="to" as the site's Mixed component does (src/premium/pages/Lessons.jsx), with the
// term list and pattern of splitMixedTonganText in src/lib/lesson-browser.js at the same commit.
const MIXED_TONGAN_TERMS = [
  'fe-...-ʻaki', 'lolotonga', 'faka-', 'taʻe-', '-ʻanga', 'ngaahi', 'totonu',
  'ʻaʻaku', 'ʻoʻoku', 'ʻanefe', 'kapau', 'hingoā', 'mou', 'ʻikai', 'pehē',
  'ʻaupito', 'ʻofa', 'ʻosi', 'ʻeni', 'ʻena', 'ʻafe', 'ʻaki', 'lava', 'tuku',
  'kiate', 'meiate', 'fie', 'kuo', 'naʻa', 'naʻe', 'ʻoku', 'siʻi', 'siʻa',
  'fuʻu', 'kiʻi', 'meia', 'taha', 'ange', 'lolotonga', 'taʻu', 'fiha', 'nga',
  '-ʻi', '-nga', 'fe-', 'ʻia', 'faka-Tonga', 'ko', 'mo', 'ki', 'mei', 'ha',
  'ʻe', 'ʻa', 'ʻi', 'ʻo', 'ke', 'ku', 'te', 'e', 'he', 'ho', 'fie', 'kei',
  'pea', 'kau', 'mai', 'atu', 'ai', 'hai', 'fe', 'pau', 'ʻanga', 'loto', 'lalo', 'kia', 'ka', 'kita',
]
const MIXED_PATTERN = new RegExp(`(?<![\\p{L}\\p{M}])(${[...new Set(MIXED_TONGAN_TERMS)].sort((a, b) => b.length - a.length).map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replaceAll('ʻ', "[ʻ'‘’ʼ`]")).join('|')})(?![\\p{L}\\p{M}])`, 'giu')
const mixedHtml = text => {
  const t = okinafy(String(text ?? '')); let out = '', end = 0
  for (const m of t.matchAll(MIXED_PATTERN)) { out += esc(t.slice(end, m.index)) + `<span lang="to">${esc(m[0])}</span>`; end = m.index + m[0].length }
  return out + esc(t.slice(end))
}
const GROUP = Object.fromEntries(COURSE.groups.map(g => [g.key, okinafy(g.name)]))

// The beat table the module plays: the sentence's beats (Storyboard.json), then the ending (reviews/bloom-middle-2026-10-09/Storyboard-Final.json).
const SEG_BEATS = (() => {
  const out = []
  for (const s of PLAY.segs) { const l = out[out.length - 1]; if (l && l.id === s.beat) l.end = s.t1; else out.push({ id: s.beat, start: s.t0, end: s.t1 }) }
  return out
})()
const timelineOf = ending => Object.freeze([...SEG_BEATS, ...ending].map(b => Object.freeze({ id: b.id, start: b.start, end: b.end })))
export const TIMELINE = timelineOf(PLAY.ending)
// The pacing bench (reviews/bloom-middle-2026-10-09/bench/, never part of the site) re-times the middle with mount(el, { ending });
// the homepage never passes it. It carries the data's ending beats, the same ids in the same order, contiguous from the page beat.
function endingOf(given) {
  if (given == null) return PLAY.ending
  const ids = PLAY.ending.map(b => b.id)
  if (!Array.isArray(given) || given.length !== ids.length) throw new Error(`ending: ${ids.length} beats expected`)
  let at = PAGE
  return Object.freeze(given.map((b, i) => {
    const start = +b.start, end = +b.end
    if (b.id !== ids[i]) throw new Error(`ending: beat ${i + 1} is ${b.id}, expected ${ids[i]}`)
    if (!(Math.abs(start - at) < 1e-6 && end > start)) throw new Error(`ending: ${b.id} does not follow on from ${at} s`)
    at = end
    return Object.freeze({ id: b.id, start, end })
  }))
}

// the middle: the stroke's walks (each to a part opener, the last to Lesson 52), the lessons already behind chip 9 (red, dim),
// the three lessons read by title while the camera holds on them
const WALKS = PLAY.ending.filter(b => /^walk-\d+$/.test(b.id)).map(b => ({ id: b.id, to: +b.id.slice(5) }))
const DIM_TO = 8, DIM_OP = 0.45, NEIGHBOURS = [8, 9, 10]
// a chip's look on the white ground: background, ring, number, and the extra ring drawn inside its 1.5 px border (2 px ahead, 3 px ringed)
const LOOK = { ahead: ['#fff', 'var(--line-strong,#d3cdc4)', 'var(--wr-muted)', 0.5], done: ['var(--wr-red)', 'var(--wr-red)', '#fff', 0], cur: ['#fff', 'var(--wr-red)', 'var(--wr-red-deep)', 1.5] }
const mixC = (a, b, k) => (k <= 0.001 ? a : k >= 0.999 ? b : `color-mix(in srgb, ${b} ${(k * 100).toFixed(1)}%, ${a})`)

const CSS = `
.sb{position:relative;font-family:var(--f-ui);color:var(--wr-ink);--sbk:1}
.sb *{box-sizing:border-box}
.sb [lang="to"]{font-family:var(--f-serif);font-style:italic;font-weight:450}
.sb-panel{position:relative;border-radius:2px;padding:18px 24px 22px}
.sb-ground{position:absolute;inset:0;border-radius:2px;background-color:${BP};background-image:linear-gradient(rgba(196,222,255,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(196,222,255,.16) 1px,transparent 1px),linear-gradient(rgba(196,222,255,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(196,222,255,.07) 1px,transparent 1px);background-size:120px 120px,120px 120px,24px 24px,24px 24px;opacity:0;pointer-events:none}
.sb-top{position:relative;z-index:3;display:flex;flex-wrap:wrap;align-items:flex-end;justify-content:space-between;gap:10px 16px;padding:0 0 6px}
.sb-flag{display:flex;align-items:baseline;gap:8px;white-space:nowrap}
.sb-flag .k{font:800 15px/1 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:var(--wr-red)}
.sb-flag .n{font:800 64px/.8 var(--f-display);color:var(--wr-red)}
.sb-flag .of{font:700 18px/1 var(--f-display);letter-spacing:.06em;text-transform:uppercase;color:var(--wr-muted)}
.sb-bphead .eb{margin:0 0 6px;color:${RING};font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}
.sb-bphead h3{margin:0;font:800 40px/.92 var(--f-display);letter-spacing:-.005em;text-transform:uppercase;color:#fff}
.sb-hd{display:grid;min-width:0;min-height:62px;align-items:end}
.sb-hd>*{grid-area:1/1}
.sb-hd>[hidden]{display:none}
.sb-ctl{display:flex;flex-wrap:wrap;gap:8px;flex-shrink:0}
.sb-btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 14px;border:1px solid var(--home-rule,#cfcfcf);border-radius:2px;background:#fff;color:var(--wr-ink);font:600 13px/1.1 var(--f-ui);cursor:pointer;white-space:nowrap}
.sb-btn:hover{border-color:var(--wr-red);color:var(--wr-red-deep)}
.sb-btn[hidden]{display:none}
.sb :focus-visible{outline:3px solid var(--wr-red-deep);outline-offset:3px;border-radius:2px}
.sb.is-dark .sb-top .sb-btn{background:transparent;color:${BPINK};border-color:rgba(196,222,255,.5)}
.sb.is-dark .sb-top .sb-btn:hover{color:#fff;border-color:#fff}
.sb.is-dark .sb-top :focus-visible,.sb.is-dark .sb-course :focus-visible{outline-color:#fff}
.sb.is-dark .sb-course .sb-ls:focus-visible{box-shadow:0 0 0 6px ${BP}}
.sb-stage{position:relative;z-index:1;overflow:hidden}
.sb-sent{position:absolute;inset:0;pointer-events:none}
.sb-en{position:absolute;left:0;right:0;top:0;margin:0}
.sb-en p{position:absolute;left:0;right:0;margin:0 auto;padding:0 8px;text-align:center;font-size:33px;line-height:1.2;color:var(--wr-ink);will-change:transform,opacity}
.sb-line{position:absolute;left:0;right:0;top:0}
.sb-cell{position:absolute;top:0;perspective:760px}
.sb-cell.drum::after{content:'';position:absolute;inset:-6px;border:3px solid var(--wr-red);border-radius:3px;transform:translateZ(2px) scale(var(--sbk));pointer-events:none}
.sb-face{position:absolute;left:0;top:0;display:grid;grid-template-rows:auto 1fr;padding:11px 18px 13px;background:#fff;border:1px solid var(--line-strong,#d3cdc4);border-bottom:3px solid var(--wr-red);border-radius:2px;box-shadow:0 10px 20px -17px rgba(35,22,16,.9);backface-visibility:hidden;white-space:nowrap}
.sb-face.off{background:var(--paper-soft,#f7f5f2);box-shadow:none}
.sb-face.new{background:color-mix(in srgb,var(--wr-red-pale) 35%,#fff)}
.sb-lab{color:var(--wr-red-deep);font:750 12px/1.1 var(--f-display);letter-spacing:.14em;text-transform:uppercase}
.sb-lab.none{visibility:hidden}
.sb-w{margin-top:6px;font-size:56px;line-height:1.05;align-self:end}
.sb-punct{position:absolute;top:0;font:italic 48px/1 var(--f-serif)}
.sb-more{position:absolute;right:0;margin:0;font:700 18px/1 var(--f-display);letter-spacing:.08em;text-transform:uppercase;color:var(--wr-muted)}
.sb-links{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}
.sb-links path{fill:none;stroke:var(--wr-red);stroke-width:1.5;stroke-dasharray:2 4;opacity:.9}
.sb-road{position:absolute;left:0;right:0;bottom:0;height:44px;display:flex;justify-content:space-between;align-items:flex-start;padding:0 2px}
.sb-road::before{content:'';position:absolute;left:0;right:0;top:6px;height:3px;background:var(--line-strong,#d3cdc4)}
.sb-stop{position:relative;width:14px;display:flex;flex-direction:column;align-items:center}
.sb-stop i{position:relative;z-index:1;width:9px;height:9px;margin-top:3px;border-radius:50%;background:#fff;border:2px solid var(--line-strong)}
.sb-stop.done i{background:var(--wr-red);border-color:var(--wr-red)}
.sb-stop.now i{width:17px;height:17px;margin-top:-1px;background:#fff;border:5px solid var(--wr-red)}
.sb-stop b{position:absolute;top:20px;font:800 14px/1 var(--f-display);color:var(--wr-muted)}
.sb-stop.done b{color:var(--wr-red)}
.sb-stop.now b{top:22px;font-size:18px;color:var(--wr-red-deep)}
.sb-gap{flex:0 0 26px;position:relative;z-index:1;height:15px;background:repeating-linear-gradient(90deg,transparent 0 4px,#fff 4px 8px)}
.sb-cards,.sb-tags{position:absolute;inset:0;pointer-events:none}
.sb-tag{position:absolute;left:0;top:0;display:block;text-align:center;color:var(--wr-ink);font:400 10.5px/1.15 var(--f-ui);hyphens:auto;-webkit-hyphens:auto;visibility:hidden;opacity:0}
.sb-tag.big{font-size:15px;font-weight:500}
.sb.is-sheet .sb-tag:not(.big){text-align:left}
.sb-card{position:absolute;left:0;top:0;display:flex;flex-direction:column;align-items:center;padding:14px 12px 44px;background:#fff;border:1px solid var(--line-strong,#d3cdc4);border-top:5px solid var(--wr-red);box-shadow:0 14px 24px -20px rgba(35,22,16,.75);text-align:center;transform-origin:50% 50%;visibility:hidden;opacity:0}
.sb-ck{align-self:flex-start;display:flex;align-items:baseline;gap:6px;font-family:var(--f-display);color:var(--wr-red);white-space:nowrap}
.sb-ck b{font-weight:800;font-size:12px;letter-spacing:.18em;text-transform:uppercase}
.sb-ck i{font-style:normal;font-weight:800;font-size:38px;line-height:.85}
.sb-cto{display:block;margin-top:auto;font-size:21px;line-height:1.14}
.sb-cen{display:block;margin:7px 0 auto;font-size:13px;line-height:1.3;color:var(--wr-muted)}
.sb-cr{position:absolute;left:0;right:0;bottom:20px;height:2px;background:var(--wr-red-pale)}
.sb-cr i{position:absolute;left:50%;top:-6px;width:14px;height:14px;margin-left:-7px;border-radius:50%;background:#fff;border:3px solid var(--wr-red-pale)}
.sb-card.cur{box-shadow:0 0 0 4px var(--wr-red),0 14px 24px -20px rgba(35,22,16,.75)}
.sb-card.cur .sb-cr{background:var(--wr-red)}
.sb-card.cur .sb-cr i{border-color:var(--wr-red)}
.sb-course{position:relative;padding:10px 8px 14px;visibility:hidden;opacity:0;color:${BPINK}}
.sb-croad{position:absolute;left:0;top:0;overflow:visible;pointer-events:none}
.sb-croad path{fill:none;stroke:${RING};stroke-width:2;stroke-opacity:.7}
.sb-cstroke{position:absolute;left:0;top:0;overflow:visible;pointer-events:none;visibility:hidden}
.sb-cstroke path{fill:none;stroke:var(--wr-red);stroke-width:3}
.sb .sb-hintc{position:relative;margin:0 0 14px;font:700 13px/1.2 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:${BPINK}}
.sb-grp{position:relative;display:grid;grid-template-columns:120px 1fr;column-gap:16px;align-items:start;margin:0 0 20px}
.sb-grp:last-child{margin-bottom:0}
.sb .sb-gname{margin:6px 0 0;font:700 13px/1.1 var(--f-display);letter-spacing:.12em;text-transform:uppercase;color:${BPINK}}
.sb-row{position:relative;display:flex;justify-content:space-between;align-items:flex-start}
.sb:not(.is-sheet) .sb-rows{padding-right:26px}
.sb-ls{position:relative;display:flex;flex-direction:column;align-items:center;min-width:44px;min-height:44px;margin:0;padding:0;border:0;background:none;color:${BPINK};font:inherit;cursor:pointer}
.sb-chip{display:block;width:28px;height:28px;border-radius:50%;border:1.5px solid ${RING};background:${BP};font:800 14px/25px var(--f-display);text-align:center;color:${BPINK}}
.sb-ttl{display:block;margin-top:5px;font:400 10.5px/1.15 var(--f-ui);text-align:center;hyphens:auto;-webkit-hyphens:auto}
.sb-ls:hover .sb-chip{border-color:#fff;color:#fff}
.sb-ls:hover .sb-ttl{color:#fff;text-decoration:underline}
.sb-ls[aria-expanded="true"] .sb-chip{background:#fff;color:${BP};border-color:#fff;box-shadow:0 0 0 4px rgba(255,255,255,.25)}
.sb.has-pv.is-docked .sb-ls:not([aria-expanded="true"]),.sb.has-pv.is-docked .sb-gname,.sb.has-pv.is-docked .sb-hintc{opacity:.65}
.sb.is-sheet .sb-grp{display:block;margin-bottom:14px}
.sb.is-sheet .sb-gname{margin:0 0 6px;padding-left:30px}
.sb.is-sheet .sb-row{justify-content:flex-start;margin-bottom:8px}
.sb.is-sheet .sb-ls{width:44px;height:44px;justify-content:center}
.sb.is-sheet .sb-chip{width:36px;height:36px;font-size:15px;line-height:33px}
.sb-pv{position:absolute;z-index:4;width:460px;background:#fff;color:var(--wr-ink);border-top:6px solid var(--wr-red);padding:18px 22px 16px;box-shadow:var(--shadow-3,0 30px 70px -20px rgba(0,0,0,.5));border-radius:2px}
.sb-pv[hidden]{display:none}
.sb .sb-pv-h{margin:0 44px 0 0;outline-offset:4px}
.sb-pv-e{display:flex;flex-wrap:wrap;gap:4px 10px;font:700 15px/1.1 var(--f-display);letter-spacing:.14em;text-transform:uppercase;color:var(--wr-red)}
.sb-pv-g{color:var(--wr-muted)}
.sb-pv-t{display:block;margin-top:5px;font:800 32px/1 var(--f-display);color:var(--wr-ink)}
.sb .sb-pv-sec{margin:13px 0 0;font:700 12px/1.1 var(--f-display);letter-spacing:.16em;text-transform:uppercase;color:var(--wr-muted)}
.sb .sb-pv ul{list-style:none;margin:6px 0 0;padding:0}
.sb-pv li{position:relative;padding-left:16px;font-size:14.5px;line-height:1.3}
.sb-pv li::before{content:'';position:absolute;left:0;top:.62em;width:8px;height:2px;background:var(--wr-red)}
.sb .sb-pv-by{margin:13px 0 0;font-size:14.5px;font-weight:600;line-height:1.3}
.sb .sb-pv-ex{margin:7px 0 0}
.sb-pv-ex [lang="to"]{display:block;font-size:20px;line-height:1.15}
.sb-pv-ex .e{display:block;margin-top:1px;font-size:13.5px;line-height:1.3;color:var(--wr-muted)}
.sb-close{position:absolute;right:8px;top:8px;width:44px;height:44px;display:flex;align-items:center;justify-content:center;border:0;background:transparent;color:var(--wr-ink);font:400 26px/1 var(--f-ui);cursor:pointer;border-radius:2px}
.sb-close:hover{color:var(--wr-red-deep)}
.sb-nav{display:flex;align-items:stretch;gap:8px;margin:14px 0 0}
.sb-nav .sb-start{flex:1}
.sb-nav .sb-btn{background:#fff;color:var(--wr-ink);border-color:var(--home-rule,#cfcfcf)}
.sb-nav .sb-btn[hidden]{display:inline-flex;visibility:hidden}
.sb-start{display:flex;align-items:center;justify-content:center;min-height:48px;padding:0 10px;text-align:center;color:#fff;background:var(--wr-red);font-size:16px;font-weight:800;letter-spacing:.02em;border-radius:2px;text-decoration:none}
.sb-start:hover{background:var(--wr-red-deep)}
.sb .sb-pv :focus-visible,.sb.is-dark .sb-course .sb-pv :focus-visible{outline-color:var(--wr-red-deep)}
.sb .sb-keys{margin:8px 0 0;font-size:12px;color:var(--wr-muted);text-align:center}
.sb-sr{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0}
.sb-measure{position:absolute;left:-9999px;top:0;visibility:hidden}
.sb.is-sheet .sb-pv{position:relative;width:auto;margin:2px 0 16px;padding:16px 16px 14px;box-shadow:0 18px 40px -18px rgba(0,0,0,.6)}
.sb.is-sheet .sb-pv-t{font-size:28px}
.sb.is-sheet .sb-pv li{font-size:14px}
.sb.is-sheet .sb-pv-by{font-size:14px}
.sb.is-sheet .sb-pv-ex [lang="to"]{font-size:19px}
.sb.is-sheet .sb-nav{flex-wrap:wrap}
.sb.is-sheet .sb-nav .sb-start{order:3;flex-basis:100%}
.sb.is-sheet .sb-nav [data-go="1"]{margin-left:auto}
.sb.is-narrow .sb-nav .sb-btn{padding:0 8px;font-size:12px}
.sb.is-narrow .sb-start{font-size:14px}
.sb.is-sheet .sb-keys{display:none}
.sb.is-narrow .sb-panel{padding:12px 6px 14px}
.sb.is-narrow .sb-hd{min-height:56px}
.sb.is-narrow .sb-ctl{width:100%}
.sb.is-narrow .sb-flag .n{font-size:46px}
.sb.is-narrow .sb-flag .k{font-size:12px}
.sb.is-narrow .sb-flag .of{font-size:14px}
.sb.is-narrow .sb-btn{padding:0 10px;font-size:12.5px}
.sb.is-narrow .sb-bphead h3{font-size:25px}
.sb.is-narrow .sb-en p{font-size:27px}
.sb.is-narrow .sb-face{padding:7px 9px 8px}
.sb.is-narrow .sb-lab{font-size:9px;letter-spacing:.08em}
.sb.is-narrow .sb-face .sb-lab{white-space:normal;max-width:72px;line-height:1.15}
.sb.is-narrow .sb-w{margin-top:3px;font-size:30px}
.sb.is-narrow .sb-punct{font-size:28px}
.sb.is-narrow .sb-more{right:auto;left:0;text-align:left;font-size:14px}
.sb.is-narrow .sb-links{z-index:-1}
.sb.is-narrow .sb-stop b{font-size:11px}
.sb.is-narrow .sb-stop.now b{font-size:14px}
.sb.is-narrow .sb-course{padding:8px 4px 10px}
.sb.is-narrow .sb-card{padding:10px 8px 36px}
.sb.is-narrow .sb-ck i{font-size:30px}
.sb.is-narrow .sb-ck b{font-size:10px}
.sb.is-narrow .sb-cto{font-size:17px}
.sb.is-narrow .sb-cen{font-size:12px}
.sb.is-tiny .sb-w{font-size:26px}
.sb.is-tiny .sb-face{padding:6px 7px 7px}
.sb.is-tiny .sb-lab{font-size:8px;letter-spacing:.06em}
.sb.is-tiny .sb-btn{padding:0 8px;font-size:12px}
@media (hover:none){.sb-keys{display:none}}
@media (prefers-reduced-motion:reduce){.sb *{transition:none!important;animation:none!important}}
`

let styleEl = null, styleRefs = 0, uid = 0
const instances = new Set()

export function mount(el, options = {}) {
  if (!el) throw new Error('mount needs an element')
  // this mount's beat table: the data's, or the bench's (checked before anything is touched)
  const ENDING = endingOf(options.ending), BEAT = Object.fromEntries(ENDING.map(b => [b.id, b])), END = ENDING[ENDING.length - 1].end
  const timeline = options.ending == null ? TIMELINE : timelineOf(ENDING)
  for (const inst of instances) if (inst.el === el) inst.destroy()
  const opt = {
    lessonHref: n => `/lessons/${n}`,
    onNavigate: null,
    startRatio: 0.6,
    ...options,
  }
  const mq = typeof matchMedia === 'function' ? matchMedia('(prefers-reduced-motion: reduce)') : null
  const reduced = opt.reducedMotion ?? (mq ? mq.matches : false)

  if (!styleEl) { styleEl = document.createElement('style'); styleEl.setAttribute('data-sentence-bloom', ''); styleEl.textContent = CSS; document.head.appendChild(styleEl) }
  styleRefs++

  // ---------- DOM ----------
  const root = h('div', 'sb')
  root.setAttribute('role', 'group')
  root.setAttribute('aria-label', 'A preview of the course: one sentence grows lesson by lesson, then all 52 lessons, each one open to preview')
  const panel = h('div', 'sb-panel')
  const ground = h('div', 'sb-ground'); ground.setAttribute('aria-hidden', 'true')
  const top = h('div', 'sb-top')
  const hd = h('div', 'sb-hd')
  const flag = h('div', 'sb-flag', '<span class="k">Lesson</span><span class="n">2</span><span class="of">of 52</span>')
  flag.setAttribute('aria-hidden', 'true')
  const chead = h('div', 'sb-bphead', '<p class="eb">The course</p><h3>Lessons 1 to 52, in order.</h3>')
  hd.append(flag, chead)
  const ctl = h('div', 'sb-ctl')
  const bPause = h('button', 'sb-btn', 'Pause'); bPause.type = 'button'
  const bReplay = h('button', 'sb-btn', 'Replay'); bReplay.type = 'button'
  const bSkip = h('button', 'sb-btn', 'Skip to the course view'); bSkip.type = 'button'
  ctl.append(bPause, bReplay, bSkip)
  top.append(hd, ctl)
  const stage = h('div', 'sb-stage')
  const sent = h('div', 'sb-sent'); sent.setAttribute('aria-hidden', 'true')
  const enBox = h('div', 'sb-en'), line = h('div', 'sb-line'), more = h('p', 'sb-more', 'Then on to Lesson 52.')
  sent.append(enBox, line, more)
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); svg.setAttribute('class', 'sb-links'); svg.setAttribute('aria-hidden', 'true')
  const road = h('div', 'sb-road'); road.setAttribute('aria-hidden', 'true')
  const STOPS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 'gap', 52]
  road.innerHTML = STOPS.map(n => n === 'gap' ? '<span class="sb-gap"></span>' : `<span class="sb-stop" data-n="${n}"><i></i>${[1, 2, 3, 4, 9, 52].includes(n) ? `<b>${n}</b>` : `<b class="opt">${n}</b>`}</span>`).join('')
  // the middle's layers, bottom to top: the course view (the road the stroke walks), the titles under the chips read in the middle,
  // and the Lesson 9 page (a lesson card, the 2026-10-08 carousel's Lesson 9, as it showed at 15.88 s)
  const cardInner = L => { const r = ROWS[L.card]; return `<span class="sb-ck"><b>Lesson</b><i>${L.n}</i></span><span class="sb-cto" lang="to" data-row="${r.id}">${esc(r.to)}</span><span class="sb-cen" data-row="${r.id}">${esc(r.en)}</span><span class="sb-cr"><i></i></span>` }
  const cardsEl = h('div', 'sb-cards'); cardsEl.setAttribute('aria-hidden', 'true')
  const page9 = h('div', 'sb-card cur', cardInner(LESSONS[8])); page9.dataset.n = 9; cardsEl.append(page9)
  const tagsEl = h('div', 'sb-tags'); tagsEl.setAttribute('aria-hidden', 'true')
  const TAGGED = [...NEIGHBOURS, ...WALKS.filter(w => w.to < 52).map(w => w.to)]
  const tags = TAGGED.map(n => { const e = h('span', 'sb-tag', esc(LESSONS[n - 1].title)); e.lang = 'en'; e.dataset.n = n; tagsEl.append(e); return e })
  const course = h('div', 'sb-course'); course.setAttribute('role', 'group'); course.setAttribute('aria-label', 'The 52 lessons, in six parts')
  stage.append(sent, svg, road, course, tagsEl, cardsEl)
  panel.append(ground, top, stage)
  const pv = h('aside', 'sb-pv')
  pv.setAttribute('aria-labelledby', 'sb-pv-h-' + (++uid))
  pv.hidden = true
  const live = h('div', 'sb-sr'); live.setAttribute('aria-live', 'polite')
  const measure = h('div', 'sb-measure'); measure.setAttribute('aria-hidden', 'true')
  root.append(panel, pv, live, measure)
  el.append(root)
  const pvId = pv.getAttribute('aria-labelledby')

  // ---------- state ----------
  let t = 0, mode = reduced ? 'end' : 'play', playing = false, userPaused = false, autoPaused = false, inView = false
  let raf = 0, last = 0, W = 0, wcls = '', geo = null, segIdx = -1, seg = null, selected = 0, pvOpen = false, destroyed = false
  let chips = [], courseKey = '', chipPos = []
  const rafReq = cb => (raf = requestAnimationFrame(cb))

  // ---------- geometry ----------
  function classify() {
    W = stage.clientWidth || root.clientWidth || 1
    const c = W >= 900 ? 'wide' : W >= 600 ? 'mid' : 'narrow'
    root.classList.toggle('is-narrow', c === 'narrow')
    root.classList.toggle('is-tiny', W < 340)
    wcls = c
    const narrow = c === 'narrow', courseWide = c === 'wide'
    root.classList.toggle('is-sheet', !courseWide)
    const perRow = Math.max(4, Math.floor((W - 8 + 10) / (44 + 10)))
    geo = { c, narrow, courseWide, perRow, playH: c === 'wide' ? 560 : c === 'mid' ? 520 : 470, roadH: 44 }
    // the Lesson 9 page: a lesson card at the 2026-10-08 carousel's size, as tall as the tallest of the 52 lesson cards at this width
    // the 2026-10-08 card size (gap and band are kept: they set the page's width on a phone)
    geo.gap = narrow ? 12 : 18; geo.band = narrow ? 8 : 26
    geo.cw = narrow ? Math.floor((W - geo.gap - 2 * (geo.band + 4)) / 2) : 200
    measure.className = 'sb-measure'
    measure.innerHTML = LESSONS.map(L => `<div class="sb-card">${cardInner(L)}</div>`).join('')
    let chMax = 0
    for (const cd of measure.children) { cd.style.width = geo.cw + 'px'; chMax = Math.max(chMax, cd.offsetHeight) }
    measure.innerHTML = ''
    geo.ch = Math.ceil(Math.max(chMax, geo.cw * (narrow ? 1.2 : 1.35)))
    page9.style.width = geo.cw + 'px'; page9.style.height = geo.ch + 'px'
    buildCourse()
    layoutCourse()
    // desktop keeps one stage height for the whole play and the ending: the play's, the course view's or the tallest preview card's
    if (courseWide) geo.playH = Math.max(geo.playH, geo.courseH, measurePvMax() + 16)
    geo.H = geo.playH
    geo.rowCy = (narrow ? geo.playH - 20 : geo.playH) / 2
    const pageW = narrow ? W * 0.78 : Math.min(W * 0.42, 460)
    geo.sPage = Math.min(pageW / geo.cw, (geo.playH - 70) / geo.ch)
    // the camera over the course view (Storyboard-Final.json frames A03 to A05): as the pull-back starts, chip 9's ring holds the whole
    // page; the neighbours' framing holds chip 9 at the middle of the stage, near where the page was; the widen ends at zoom 1
    geo.Z0 = Math.max(courseWide ? 20 : 13, 1.05 * geo.ch * geo.sPage / (2 * geo.chipR))
    geo.edge = narrow ? 14 : 26
    const step = Math.abs(chipPos[9].x - chipPos[8].x)
    geo.ZN = courseWide ? 2.4 : Math.min(2.0, (W / 2 - 3 - geo.edge) / (step + geo.chipR))
    geo.nPos = { x: W / 2, y: geo.rowCy + (courseWide ? -36 : 7) }
    if (pvOpen) renderPv(false)
  }
  function measurePvMax() {
    if (!geo.courseWide) return 0
    const keep = { sel: selected, open: pvOpen, hidden: pv.hidden, vis: pv.style.visibility }
    pv.hidden = false; pv.style.visibility = 'hidden'
    let mx = 0
    for (const L of LESSONS) { pv.innerHTML = pvHtml(L.n); mx = Math.max(mx, pv.offsetHeight) }
    pv.style.visibility = keep.vis; pv.hidden = keep.hidden
    if (keep.open) pv.innerHTML = pvHtml(keep.sel)
    return mx
  }

  // ---------- the course view: the site's six named parts, every row left to right ----------
  function buildCourse() {
    const key = geo.courseWide ? 'w' : 'n' + geo.perRow
    if (courseKey === key) return
    courseKey = key
    if (pv.parentNode !== root) root.insertBefore(pv, live)
    course.innerHTML = ''
    const roadSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); roadSvg.setAttribute('class', 'sb-croad'); roadSvg.setAttribute('aria-hidden', 'true')
    // the red stroke the middle walks along the road (hidden in the course view)
    const strokeSvg = document.createElementNS('http://www.w3.org/2000/svg', 'svg'); strokeSvg.setAttribute('class', 'sb-cstroke'); strokeSvg.setAttribute('aria-hidden', 'true')
    const hint = h('p', 'sb-hintc', geo.courseWide ? 'Click a lesson to see what it teaches.' : 'Tap a lesson to see what it teaches.')
    course.append(roadSvg, strokeSvg, hint)
    chips = []
    for (const G of COURSE.groups) {
      const grp = h('div', 'sb-grp'); grp.setAttribute('role', 'group'); grp.setAttribute('aria-label', okinafy(G.name)); grp.dataset.group = G.key
      const nm = h('p', 'sb-gname', esc(okinafy(G.name))); nm.setAttribute('aria-hidden', 'true')
      const box = h('div', 'sb-rows')
      const per = geo.courseWide ? G.lessons.length : geo.perRow
      for (let i = 0; i < G.lessons.length; i += per) {
        const row = h('div', 'sb-row')
        for (const n of G.lessons.slice(i, i + per)) {
          const L = LESSONS[n - 1]
          const b = h('button', 'sb-ls', `<span class="sb-chip" aria-hidden="true">${n}</span>${geo.courseWide ? `<span class="sb-ttl" lang="en" aria-hidden="true">${esc(L.title)}</span>` : ''}`)
          b.type = 'button'; b.dataset.n = n
          b.setAttribute('aria-label', `Lesson ${n}: ${L.title}`)
          b.setAttribute('aria-expanded', 'false')
          row.append(b); chips[n - 1] = b
        }
        box.append(row)
      }
      grp.append(nm, box); course.append(grp)
    }
    course._road = roadSvg; course._stroke = strokeSvg
  }
  // measured once per width: where each chip sits, the road through them, and the course view's height
  function layoutCourse() {
    const wasOpen = pv.parentNode === course || (pv.parentNode && pv.parentNode.closest && pv.parentNode.closest('.sb-course'))
    if (wasOpen) root.insertBefore(pv, live)
    // measured untransformed (the middle's camera moves the course element; the next render puts it back)
    course.style.transform = ''
    chips.forEach(b => { b.firstChild.style.transform = '' })
    const rowsEls = [...course.querySelectorAll('.sb-row')]
    if (geo.courseWide) {
      const trackW = course.clientWidth - 16 - 120 - 16 - 26
      for (const row of rowsEls) { const n = row.children.length, tw = Math.max(44, Math.min(112, Math.floor(trackW / n) - 4)); for (const b of row.children) b.style.width = tw + 'px'; row.style.gap = '' }
    } else {
      const cw = course.clientWidth - 8, per = geo.perRow, g = per > 1 ? Math.min(14, Math.floor((cw - per * 44) / (per - 1))) : 0
      for (const row of rowsEls) { row.style.gap = g + 'px'; for (const b of row.children) b.style.width = '' }
    }
    const cr = course.getBoundingClientRect(), sr = stage.getBoundingClientRect()
    const offX = cr.left - sr.left, offY = cr.top - sr.top
    chipPos = chips.map(b => { const r = b.firstChild.getBoundingClientRect(); return { x: r.left + r.width / 2 - cr.left, y: r.top + r.height / 2 - cr.top } })
    geo.courseOff = { x: offX, y: offY }
    // the road: along each row, then back under it to the next row's first lesson, like a line of text
    // (the middle's stroke draws the same road as one continuous path, measured to every chip as it is built)
    let d = '', ds = '', len = 0
    const chipLen = new Array(52).fill(0)
    const bez = (...p) => { let s = 0, q = p[0]; for (let k = 1; k <= 32; k++) { const u = k / 32, v = 1 - u, w = p.length === 3 ? [v * v, 2 * v * u, u * u] : [v * v * v, 3 * v * v * u, 3 * v * u * u, u * u * u]; const x = w.reduce((a, c, j) => a + c * p[j][0], 0), y = w.reduce((a, c, j) => a + c * p[j][1], 0); s += Math.hypot(x - q[0], y - q[1]); q = [x, y] } return s }
    const rows = rowsEls.map(row => { const ns = [...row.children].map(b => +b.dataset.n); const rr = row.getBoundingClientRect(); return { ns, bottom: rr.bottom - cr.top } })
    rows.forEach((r, i) => {
      const a = chipPos[r.ns[0] - 1], b = chipPos[r.ns[r.ns.length - 1] - 1]
      d += `M${a.x.toFixed(1)} ${a.y.toFixed(1)} L${b.x.toFixed(1)} ${b.y.toFixed(1)} `
      ds += `${i ? '' : `M${a.x.toFixed(1)} ${a.y.toFixed(1)} `}L${b.x.toFixed(1)} ${b.y.toFixed(1)} `
      for (const n of r.ns) chipLen[n - 1] = len + Math.hypot(chipPos[n - 1].x - a.x, chipPos[n - 1].y - a.y)
      len += Math.hypot(b.x - a.x, b.y - a.y)
      const nx = rows[i + 1]
      if (nx) {
        // desktop: the turn runs down beside the last title, not through it
        const c = chipPos[nx.ns[0] - 1], gy = r.bottom + (geo.courseWide ? 9 : 4), bend = geo.courseWide ? 18 : 12
        const lastB = chips[r.ns[r.ns.length - 1] - 1], xr = geo.courseWide ? b.x + lastB.offsetWidth / 2 + 12 : b.x + bend
        const turn = `L${(xr - 10).toFixed(1)} ${b.y.toFixed(1)} Q${xr.toFixed(1)} ${b.y.toFixed(1)} ${xr.toFixed(1)} ${(b.y + 10).toFixed(1)} L${xr.toFixed(1)} ${(gy - 10).toFixed(1)} Q${xr.toFixed(1)} ${gy.toFixed(1)} ${(xr - 10).toFixed(1)} ${gy.toFixed(1)} L${c.x.toFixed(1)} ${gy.toFixed(1)} C${(c.x - bend).toFixed(1)} ${gy.toFixed(1)} ${(c.x - bend).toFixed(1)} ${c.y.toFixed(1)} ${c.x.toFixed(1)} ${c.y.toFixed(1)} `
        d += `M${b.x.toFixed(1)} ${b.y.toFixed(1)} ` + turn
        ds += turn
        len += Math.abs(xr - 10 - b.x) + bez([xr - 10, b.y], [xr, b.y], [xr, b.y + 10]) + Math.abs(gy - b.y - 20) + bez([xr, gy - 10], [xr, gy], [xr - 10, gy]) + Math.abs(xr - 10 - c.x) + bez([c.x, gy], [c.x - bend, gy], [c.x - bend, c.y], [c.x, c.y])
      }
    })
    const rs = course._road
    rs.setAttribute('width', Math.ceil(cr.width)); rs.setAttribute('height', Math.ceil(cr.height))
    rs.innerHTML = `<path d="${d}"/>`
    const ss = course._stroke
    ss.setAttribute('width', Math.ceil(cr.width)); ss.setAttribute('height', Math.ceil(cr.height))
    ss.innerHTML = `<path d="${ds}" pathLength="${len.toFixed(2)}"/>`
    geo.chipLen = chipLen; geo.roadLen = len
    geo.chipR = chips[0].firstChild.offsetWidth / 2
    // each part name's text box (course coordinates), so it can fade at the stage's edge while the camera is in
    geo.nameBox = [...course.querySelectorAll('.sb-gname')].map(e => { const rg = document.createRange(); rg.selectNodeContents(e); const b = rg.getBoundingClientRect(); return { x: b.left - cr.left, y: b.top - cr.top, w: b.width, h: b.height } })
    geo.courseH = Math.ceil(course.offsetHeight)
    geo.rowsOf = rows.map(r => r.ns)
    if (wasOpen && pvOpen) placePv()
  }

  // ---------- the sentence ----------
  function face(r, k, cls = '') {
    const w = r.words[k]
    const lab = w[1] ? `<span class="sb-lab" data-src="${esc(srcText(w[2]))}" title="${esc(srcText(w[2]))}">${esc(w[1])}</span>` : '<span class="sb-lab none">label</span>'
    return `<div class="sb-face ${cls}" data-row="${r.id}" data-i="${k}">${lab}<span class="sb-w" lang="to" data-row="${r.id}" data-i="${k}">${esc(w[0])}</span></div>`
  }
  const sizeCache = new Map()
  function faceSize(r, k) {
    const key = wcls + (W < 340 ? 't' : '') + r.id + ':' + k
    if (sizeCache.has(key)) return sizeCache.get(key)
    measure.className = 'sb-measure'
    measure.innerHTML = face(r, k)
    const f = measure.firstChild; f.style.position = 'static'; f.style.display = 'inline-grid'
    const s = { w: f.offsetWidth, h: f.offsetHeight }
    measure.innerHTML = ''
    sizeCache.set(key, s); return s
  }
  function textH(html, width, cls) {
    measure.innerHTML = `<div class="sb-en" style="position:static;width:${width}px"><p style="position:static" class="${cls || ''}">${html}</p></div>`
    const hgt = measure.firstChild.firstChild.offsetHeight; measure.innerHTML = ''; return hgt
  }
  // one width per slot across the spins, the turn and the describing word, so the sentence never jumps sideways there
  let groupW = null, groupH = 0
  function groupWidths() {
    const wv = [0, 0, 0]; groupH = 0
    for (const s of PLAY.segs) { if (s.rows.some(id => ROWS[id].words.length !== 3)) continue; for (const id of s.rows) for (let k = 0; k < 3; k++) { const z = faceSize(ROWS[id], k); wv[k] = Math.max(wv[k], z.w) } }
    // one tile height for the whole play, so no tile changes height between beats
    for (const s of PLAY.segs) for (const id of s.rows) ROWS[id].words.forEach((_, k) => { groupH = Math.max(groupH, faceSize(ROWS[id], k).h) })
    return wv
  }
  const segGroup = s => s.rows.every(id => ROWS[id].words.length === 3) && !(s.k === 'morph' && s.keys[1].length !== 3)

  // the widths each slot ends a segment with, derived from the timeline and the current width (never from what was drawn before)
  function endWidths(i) {
    const d = PLAY.segs[i], out = {}
    if (!d) return out
    if (d.k === 'drum') { for (let k = 0; k < ROWS[d.rows[0]].words.length; k++) out[['T', 'P', 'V'][k]] = groupW[k]; return out }
    const B = ROWS[d.rows[1]]
    d.keys[1].forEach((key, ib) => { out[key] = segGroup(d) ? groupW[ib] : faceSize(B, ib).w })
    return out
  }
  function buildSeg(i) {
    // this mount's own working copy of the segment: cells, measurements and layouts live here, not in the imported data
    seg = { ...PLAY.segs[i] }; segIdx = i
    const s = seg, gap = geo.narrow ? 8 : 10
    line.innerHTML = ''; enBox.innerHTML = ''
    const cells = []
    if (s.k === 'drum') {
      const R = s.rows.map(id => ROWS[id])
      for (let k = 0; k < R[0].words.length; k++) {
        const isDrum = s.cells.includes(k)
        const c = h('div', 'sb-cell' + (isDrum ? ' drum' : ''))
        c.innerHTML = R.map(r => face(r, k)).join('')
        c._faces = [...c.children]
        c._type = isDrum ? 'drum' : 'follow'
        c._learned = s.learned[k]
        const w = groupW[k], hh = groupH
        c._wA = c._wB = w; c._h = hh
        c._faces.forEach(f => { f.style.width = w + 'px'; f.style.height = hh + 'px' })
        cells.push(c)
      }
      s._en = R.map(r => r.en)
    } else {
      const A = ROWS[s.rows[0]], B = ROWS[s.rows[1]], [KA, KB] = s.keys
      const order = []
      KB.forEach(k => order.push(k))
      KA.forEach((k, i2) => { if (!KB.includes(k)) { const prev = KA[i2 - 1]; order.splice(prev ? order.indexOf(prev) + 1 : 0, 0, k) } })
      const prevW = endWidths(i - 1)
      for (const key of order) {
        const ia = KA.indexOf(key), ib = KB.indexOf(key)
        const c = h('div', 'sb-cell')
        let type
        if (ia >= 0 && ib >= 0) {
          const same = A.words[ia][0] === B.words[ib][0] && (A.words[ia][1] || '') === (B.words[ib][1] || '')
          type = same ? 'static' : 'roll'
          const pink = KA.length !== KB.length && s.learned[ib] === s.lesson ? 'new' : ''
          c.innerHTML = same ? face(B, ib).replace('data-row="' + B.id + '" data-i', `data-rows="${A.id} ${B.id}" data-row="${B.id}" data-i`) : face(A, ia) + face(B, ib, pink)
        } else if (ib >= 0) { type = 'grow'; c.innerHTML = face(B, ib, 'new') } else { type = 'shrink'; c.innerHTML = face(A, ia) }
        c._faces = [...c.children]; c._type = type; c._key = key
        const sa = ia >= 0 ? faceSize(A, ia) : { w: 0, h: 0 }, sb = ib >= 0 ? faceSize(B, ib) : { w: 0, h: 0 }
        c._wA = ia >= 0 ? (prevW[key] ?? sa.w) : 0
        c._wB = ib >= 0 ? (segGroup(s) ? groupW[ib] : sb.w) : 0
        c._h = groupH
        c._learned = ib >= 0 ? s.learned[ib] : (PLAY.segs[i - 1] ? PLAY.segs[i - 1].learned[ia] : s.learned[0])
        c._faces.forEach((f, j) => { const fw = c._faces.length === 2 ? (j === 0 ? sa.w : sb.w) : (type === 'shrink' ? sa.w : sb.w); f.style.width = Math.max(fw, 0) + 'px'; f.style.height = c._h + 'px' })
        cells.push(c)
      }
      s._en = [A.en, B.en]
    }
    cells.forEach(c => line.append(c))
    const punct = h('div', 'sb-punct', esc(ROWS[s.rows[0]].punct)); line.append(punct)
    seg._cells = cells; seg._punct = punct
    // the English ring
    const enW = W - 8
    seg._enH = Math.max(...s._en.map(e => textH(esc(e), enW)))
    enBox.innerHTML = s._en.map((e, j) => `<p data-row="${s.rows[j]}">${esc(e)}</p>`).join('')
    seg._ens = [...enBox.children]
    enBox.style.height = seg._enH + 'px'
    seg._ens.forEach(p => { p.style.width = enW + 'px' })
    // line layouts at the start and the end of the segment
    const tileH = Math.max(...cells.map(c => c._h))
    seg._tileH = tileH
    // a three-slot sentence always sits on one line, scaled down if the screen is too narrow for it
    const natural = ws => ws.reduce((a, w) => a + w, 0) + gap * (ws.filter(w => w > 0).length - 1) + 24
    const avail = W - 24
    seg._fitA = segGroup(s) || (s.k === 'morph' && cells.every(c => c._wA === 0 || c._type !== 'grow') && s.keys[0].length === 3) ? Math.min(1, avail / natural(cells.map(c => c._wA))) : 1
    seg._fitB = segGroup(s) ? Math.min(1, avail / natural(cells.map(c => c._wB))) : 1
    seg._rowsA = segGroup(s) || seg._fitA < 1 ? [cells.map((_, i) => i)] : rowsOf(cells.map(c => c._wA), gap, avail)
    seg._rowsB = segGroup(s) ? [cells.map((_, i) => i)] : rowsOf(cells.map(c => c._wB), gap, avail)
    seg._gap = gap
  }
  function rowsOf(ws, gap, avail) {
    const rows = [[]]; let x = 0
    ws.forEach((w, i) => { if (w > 0 && x > 0 && x + w > avail) { rows.push([]); x = 0 } rows[rows.length - 1].push(i); if (w > 0) x += w + gap })
    return rows
  }
  function place(ws, rows, gap, tileH, fit) {
    const pos = new Array(ws.length), rowGap = geo.narrow ? 12 : 16, ww = W / fit
    let end = null
    rows.forEach((r, ri) => {
      const g = r.map(i => gap * Math.min(1, ws[i] / 30))
      const tot = r.reduce((a, i, k) => a + ws[i] + (k < r.length - 1 ? g[k] : 0), 0)
      let xx = (ww - tot) / 2 - 8
      r.forEach((i, k) => { pos[i] = { x: xx, y: ri * (tileH + rowGap) }; xx += ws[i] + (k < r.length - 1 ? g[k] : 0) })
      if (ri === rows.length - 1) end = { x: xx + 4, y: ri * (tileH + rowGap) }
    })
    // scale about the centre of the stage
    const k = fit, cx = ww / 2
    pos.forEach(p => { p.x = W / 2 + (p.x - cx) * k; p.y *= k })
    end.x = W / 2 + (end.x - cx) * k; end.y *= k
    return { pos, h: (rows.length * tileH + (rows.length - 1) * rowGap) * k, punct: end }
  }
  function posAt(moves, tt) {
    let p = moves[0][2]
    for (const [t0, t1, p0, p1] of moves) { if (tt < t0) return p; if (tt < t1) return p0 + (p1 - p0) * E((tt - t0) / (t1 - t0)); p = p1 }
    return p
  }
  const wrapD = (d, n) => { d = ((d % n) + n) % n; return d > n / 2 ? d - n : d }
  function pulseAt(moves, tt) { for (const m of moves) { const d = tt - m[1]; if (d >= 0 && d < 0.24) return 1 + 0.07 * Math.sin(Math.PI * d / 0.24) } return 1 }

  function drumFaces(c, pos, v) {
    const n = c._faces.length, H = c._h, step = 34
    const R = H / 2 / Math.tan(step / 2 * Math.PI / 180), reach = 2.4
    const blur = v > 5 ? Math.min(1.3, (v - 5) * 0.13) : 0
    c._faces.forEach((f, i) => {
      const d = n === 2 ? i - pos : wrapD(i - pos, n), ad = Math.abs(d)
      f.style.transform = `translateZ(${-R}px) rotateX(${-d * step}deg) translateZ(${R}px)`
      if (ad > reach) { f.style.visibility = 'hidden'; f.style.opacity = 0; f.classList.remove('win'); f.classList.add('off'); f.lastChild.style.filter = ''; return }
      const op = clamp(1 - 0.38 * ad) * (ad > reach - 0.4 ? (reach - ad) / 0.4 : 1)
      f.style.opacity = op; f.style.visibility = op > 0.01 ? 'visible' : 'hidden'
      f.classList.toggle('off', ad >= 0.5); f.classList.toggle('win', ad < 0.5)
      const w = f.lastChild; w.style.filter = blur ? `blur(${blur.toFixed(2)}px)` : ''
    })
  }
  function showOnly(c, j) { c._faces.forEach((f, i) => { f.style.transform = ''; f.style.opacity = i === j ? 1 : 0; f.style.visibility = i === j ? 'visible' : 'hidden'; f.classList.toggle('win', i === j) }) }

  function renderSentence(tt) {
    let i = PLAY.segs.findIndex(s => tt >= s.t0 && tt < s.t1)
    if (i < 0) i = PLAY.segs.length - 1
    if (i !== segIdx) buildSeg(i) // a morph starts at the widths the previous segment ends with (endWidths)
    const s = seg, n = s.rows.length
    let pos, e, k = 1, v = 0
    if (s.k === 'drum') { pos = posAt(s.moves, tt); v = Math.abs(posAt(s.moves, tt + 0.02) - pos) / 0.02; k = pulseAt(s.moves, tt); e = 0 }
    else { e = E(span(s.s0, s.s1, tt)); pos = e; k = pulseAt([[s.s0, s.s1]], tt) }
    root.style.setProperty('--sbk', k.toFixed(3))
    const shown = ((Math.round(pos) % n) + n) % n
    const ee = s.k === 'morph' ? smooth(span(s.s0, s.s1, tt)) : 0
    const wsNow = s._cells.map(c => lerp(c._wA, c._wB, ee))
    const fit = lerp(s._fitA, s._fitB, ee)
    const LA = place(wsNow, s._rowsA, s._gap, s._tileH, fit), LB = place(wsNow, s._rowsB, s._gap, s._tileH, fit)
    s._fit = fit
    // vertical placement: the English sits above the tiles; a turning drum needs room for its neighbours
    const drumRoom = segGroup(s) || (s.k === 'morph' && s.rows[0] === 'ch03-l027-0') ? (geo.narrow ? 84 : 112) : 0
    const roomNow = s.rows[0] === 'ch03-l027-0' && s.k === 'morph' ? lerp(drumRoom, 0, ee) : (segGroup(s) ? drumRoom : 0)
    const enGap = (geo.narrow ? 18 : 22) + roomNow
    const blockH = lerp(LA.h, LB.h, ee)
    const area = geo.playH - geo.roadH - 30
    const totalH = s._enH + enGap + blockH
    const y0 = Math.max(roomNow * 0.25, (area - totalH) / 2 + (geo.narrow ? 0 : 6))
    enBox.style.transform = `translateY(${y0}px)`
    line.style.top = (y0 + s._enH + enGap) + 'px'
    s._lineTop = y0 + s._enH + enGap
    s._cells.forEach((c, ci) => {
      const a = LA.pos[ci], b = LB.pos[ci]
      const x = lerp(a.x, b.x, ee), y = lerp(a.y, b.y, ee)
      const w = wsNow[ci]
      c.style.transform = `translate(${x.toFixed(1)}px,${y.toFixed(1)}px) scale(${fit.toFixed(4)})`
      c.style.transformOrigin = '0 0'
      c.style.width = w + 'px'; c.style.height = c._h + 'px'
      c._x = x; c._y = y; c._w = w * fit; c._hs = c._h * fit
      if (c._type === 'drum') drumFaces(c, pos, v)
      else if (c._type === 'follow') showOnly(c, shown)
      else if (c._type === 'roll') {
        drumFaces(c, pos, v)
        const moving = tt >= s.s0 && tt < s.s1 + 0.24
        c.classList.toggle('drum', moving)
        const mid = 1 - Math.abs(2 * ee - 1)
        c._faces.forEach(f => { f.style.left = (w - parseFloat(f.style.width)) / 2 + 'px'; if (!f.classList.contains('win')) { const o = +f.style.opacity * mid; f.style.opacity = o; f.style.visibility = o > 0.01 ? 'visible' : 'hidden' } })
      }
      else if (c._type === 'static') showOnly(c, 0)
      // an arriving (or leaving) word unfolds with its slot rather than being cut by the slot's edge: no painted text is ever clipped
      else if (c._type === 'grow') { const op = clamp((e - 0.5) * 2.5); const f = c._faces[0], sx = clamp(w / (parseFloat(f.style.width) || 1), 0.001, 1); f.style.opacity = op; f.style.visibility = e >= 0.5 ? 'visible' : 'hidden'; f.style.transformOrigin = '0 0'; f.style.transform = `translateY(${((1 - op) * -14).toFixed(1)}px) scaleX(${sx.toFixed(4)})`; f.style.left = '0px' }
      else if (c._type === 'shrink') { const op = 1 - clamp(e * 2.5); const f = c._faces[0], sx = clamp(w / (parseFloat(f.style.width) || 1), 0.001, 1); f.style.opacity = op; f.style.visibility = e < 0.5 && op > 0.01 ? 'visible' : 'hidden'; f.style.transformOrigin = '0 0'; f.style.transform = `scaleX(${sx.toFixed(4)})`; f.style.left = '0px' }
      c._live = c._type !== 'shrink' ? (c._type !== 'grow' || e >= 0.5) : e < 0.5
    })
    const pA = LA.punct, pB = LB.punct
    s._punct.style.transform = `translate(${lerp(pA.x, pB.x, ee).toFixed(1)}px,${(lerp(pA.y, pB.y, ee) + (s._tileH - (geo.narrow ? 34 : 56)) * fit).toFixed(1)}px) scale(${fit.toFixed(4)})`
    s._punct.style.transformOrigin = '0 0'
    // the English rolls in step with the slot
    const H = s._enH
    s._ens.forEach((p, j) => {
      const d = n === 2 && s.k === 'morph' ? j - pos : wrapD(j - pos, n), ad = Math.abs(d)
      const op = clamp(1 - ad * 1.1)
      p.style.opacity = op; p.style.visibility = op > 0.01 ? 'visible' : 'hidden'
      p.style.transform = `translateY(${(d * H * 0.8).toFixed(1)}px)`
      p.classList.toggle('settled', ad < 0.02)
    })
    s._shown = shown
    // "Then on to Lesson 52."
    const mo = s.more ? clamp((tt - s.more) / 0.3) : 0
    more.style.opacity = mo; more.style.visibility = mo > 0 ? 'visible' : 'hidden'
    more.style.top = (geo.playH - geo.roadH - (geo.narrow ? 30 : 36)) + 'px'
    return s
  }

  // ---------- lesson flag, road and links ----------
  function lessonAt(tt) {
    if (tt >= PLAY.page) return 9
    const s = PLAY.segs.find(x => tt >= x.t0 && tt < x.t1) || PLAY.segs[PLAY.segs.length - 1]
    return s.lesson
  }
  let flagN = -1
  function renderRoad(n) {
    if (n !== flagN) {
      flag.querySelector('.n').textContent = n
      road.querySelectorAll('.sb-stop').forEach(st => { const k = +st.dataset.n; st.classList.toggle('done', k <= n && k !== 52); st.classList.toggle('now', k === n); const b = st.querySelector('b.opt'); if (b) b.style.visibility = k === n ? 'visible' : 'hidden' })
      flagN = n; stopX = null
    }
  }
  let stopX = null
  function stopCenters() {
    if (stopX) return stopX
    const box = stage.getBoundingClientRect()
    stopX = {}
    road.querySelectorAll('.sb-stop').forEach(st => { const r = st.querySelector('i').getBoundingClientRect(); stopX[st.dataset.n] = { x: r.left + r.width / 2 - box.left, y: r.top - box.top - 2 } })
    return stopX
  }
  function drawLinks(s, n, op) {
    if (op <= 0 || !s) { svg.innerHTML = ''; return }
    const sc = stopCenters(); let p = ''
    for (const [ci, c] of s._cells.entries()) {
      if (!c._live || c._w < 2) continue
      if (geo.narrow && c._learned !== n) continue
      const st = sc[c._learned]; if (!st) continue
      const x1 = c._x + c._w / 2, y1 = s._lineTop + c._y + c._hs + (c.classList.contains('drum') ? 8 : 2)
      const my = (y1 + st.y) / 2
      c.dataset.ci = ci
      p += `<path data-ci="${ci}" d="M${x1.toFixed(1)} ${y1.toFixed(1)} C ${x1.toFixed(1)} ${my.toFixed(1)}, ${st.x.toFixed(1)} ${my.toFixed(1)}, ${st.x.toFixed(1)} ${st.y.toFixed(1)}"/>`
    }
    svg.innerHTML = p; svg.style.opacity = op
  }

  // ---------- the middle (reviews/bloom-middle-2026-10-09/Storyboard-Final.json, direction A) ----------
  // The world is the course view itself: its chips, road and part names, drawn white and red and moved by a camera (a transform on the
  // course element). The walk lands on the course view by turning blue in place, so nothing is swapped at the end.
  const p9 = () => chipPos[8]
  // the camera: chip 9 put at stage point (x, y), zoom Z; u runs 0 to 1 over the pull-back and 1 to 2 over the widen
  function camAt(tt) {
    const pb = BEAT.pullback, wd = BEAT.widen, Z0 = geo.Z0, ZN = geo.ZN, np = geo.nPos
    const pc = { x: W / 2, y: geo.rowCy }, home = { x: geo.courseOff.x + p9().x, y: geo.courseOff.y + p9().y }
    if (tt < pb.end) { const u = smooth(span(pb.start, pb.end, tt)); return { Z: Z0 * Math.pow(ZN / Z0, u), x: lerp(pc.x, np.x, u), y: lerp(pc.y, np.y, u), u } }
    if (tt < wd.start) return { Z: ZN, x: np.x, y: np.y, u: 1 }
    if (tt < wd.end) { const u = smooth(span(wd.start, wd.end, tt)); return { Z: Math.pow(ZN, 1 - u), x: lerp(np.x, home.x, u), y: lerp(np.y, home.y, u), u: 1 + u } }
    return { Z: 1, x: home.x, y: home.y, u: 2 }
  }
  // where a point of the course view (course coordinates) is on the stage under the camera
  const onStage = (cam, p) => ({ x: cam.x + (p.x - p9().x) * cam.Z, y: cam.y + (p.y - p9().y) * cam.Z })
  // the fade at the stage's edge for a box on the stage (over geo.edge px): nothing painted is ever cut by the edge while the camera is in
  const edge = (l, tp, r, b, H) => clamp((Math.min(l, W - r, tp, H - b) - 3) / geo.edge)
  // the stroke's head, a length along the road: at chip 9; a short lead out of it as the camera arrives; then each walk eases to its
  // part opener (the first starting at the lead's speed) and the head rests there through the hold
  function headAt(tt) {
    const L = n => geo.chipLen[n - 1], wd = BEAT.widen, t0 = wd.start + 0.25 * (wd.end - wd.start), lead = 0.8 * (L(10) - L(9))
    if (tt < t0) return L(9)
    if (tt < wd.end) return L(9) + lead * span(t0, wd.end, tt)
    let from = L(9) + lead, v0 = lead / (wd.end - t0)
    for (const w of WALKS) {
      const b = BEAT[w.id], to = L(w.to)
      if (tt < b.start) return from
      if (tt < b.end) {
        const u = span(b.start, b.end, tt), dist = Math.max(1e-6, to - from), m0 = clamp(v0 * (b.end - b.start) / dist, 0, 3)
        return from + dist * (m0 * (u * u * u - 2 * u * u + u) + u * u * (3 - 2 * u))
      }
      from = to; v0 = 0
    }
    return from
  }
  // the flag's lesson: the sentence's, then 9, then the last chip the stroke has reached
  function counterLesson(tt) {
    if (tt < PAGE) return lessonAt(tt)
    if (tt < BEAT.widen.start) return 9
    const head = headAt(tt) + 2
    let n = 9
    while (n < 52 && geo.chipLen[n] <= head) n++
    return n
  }
  // a chip's look, as two looks and the mix between them: Lessons 1 to 8 red (dim); chip 9 and each part opener ringed from the
  // stroke's arrival until the walk goes on, then red; every other chip lit red as the stroke's head passes it
  function chipLook(n, tt, head) {
    if (n <= DIM_TO) return ['done', 'done', 0]
    const wi = WALKS.findIndex(w => w.to === n)
    if (n === 9 || wi >= 0) {
      const next = WALKS[n === 9 ? 0 : wi + 1]
      const leave = next ? smooth(span(BEAT[next.id].start, BEAT[next.id].start + 0.15, tt)) : 0
      if (leave > 0) return ['cur', 'done', leave]
      if (n === 9) return ['cur', 'cur', 0]
      const end = BEAT[WALKS[wi].id].end
      return ['ahead', 'cur', smooth(span(end - 0.15, end - 0.03, tt))]
    }
    return ['ahead', 'done', clamp((head - geo.chipLen[n - 1] + 6) / 36)]
  }
  // the part names: Foundations and Core Grammar as the camera arrives; each later part as the stroke reaches its first lesson, red
  // through that hold
  function nameAt(gi, tt) {
    const hold = BEAT['hold-' + COURSE.groups[gi].lessons[0]], wd = BEAT.widen
    if (!hold) return { op: smooth(span(wd.start + 0.7 * (wd.end - wd.start), wd.end, tt)), red: 0 }
    return { op: smooth(span(hold.start - 0.2, hold.start, tt)), red: 1 - smooth(span(hold.end, hold.end + 0.25, tt)) }
  }
  // the Lesson 9 page: fades in as the sentence goes (as on 2026-10-08), holds, then shrinks with the camera into chip 9's ring and fades
  function renderPage(tt) {
    const pb = BEAT.pullback
    if (!(tt >= PAGE && tt < pb.end)) { page9.style.visibility = 'hidden'; page9.style.opacity = 0; return }
    let s = geo.sPage, x = W / 2, y = geo.rowCy, op = smooth(span(PAGE + 0.05, PAGE + 0.45, tt))
    if (tt >= pb.start) { const c = camAt(tt); s *= c.Z / geo.Z0; x = c.x; y = c.y; op *= 1 - smooth(span(0.66, 0.86, c.u)) }
    page9.style.transform = `translate(${(x - geo.cw / 2).toFixed(1)}px,${(y - geo.ch / 2).toFixed(1)}px) rotate(0.00deg) scale(${s.toFixed(4)})`
    page9.style.opacity = op.toFixed(3); page9.style.visibility = op > 0.003 ? 'visible' : 'hidden'; page9.style.zIndex = 60
  }
  // the middle's own styling on the course view, all of it inline, cleared whenever the course view shows as itself
  function clearWalk() {
    if (course.inert) course.inert = false
    course.style.transform = ''; course.style.transformOrigin = ''
    for (const b of chips) { const s = b.firstChild.style; s.backgroundColor = s.borderColor = s.color = s.boxShadow = '' }
    for (const e of course.querySelectorAll('.sb-gname')) e.style.color = ''
    const rp = course._road.firstChild; if (rp) rp.style.stroke = rp.style.strokeOpacity = rp.style.strokeWidth = ''
    course._stroke.style.visibility = 'hidden'; course._stroke.style.opacity = 0
  }
  // the course view: hidden until the pull-back; the middle's world from there; blue in place through the turn; from the end of the
  // turn exactly the course view of 2026-10-08, its titles, hint and heading fading up in the course beat as they did. Returns the camera.
  function renderCourse(tt, H) {
    const pb = BEAT.pullback, wd = BEAT.widen, nb = BEAT.neighbours, turn = BEAT.turn
    if (tt < pb.start) { clearWalk(); course.inert = true; course.style.visibility = 'hidden'; course.style.opacity = 0; return null }
    course.style.visibility = 'visible'; course.style.opacity = smooth(span(pb.start, pb.start + 0.45, tt)).toFixed(3)
    const rest = smooth(span(BEAT.course.start - 0.15, BEAT.course.end - 0.1, tt))
    for (const b of chips) { const ttl = b.children[1]; if (ttl) { ttl.style.opacity = rest.toFixed(3); ttl.style.visibility = rest > 0.003 ? 'visible' : 'hidden' } }
    for (const e of course.querySelectorAll('.sb-hintc')) { e.style.opacity = rest.toFixed(3); e.style.visibility = rest > 0.003 ? 'visible' : 'hidden' }
    course._road.style.opacity = 1; course._road.style.visibility = 'visible'
    if (tt >= turn.end) {
      clearWalk()
      for (const b of chips) { const ch = b.firstChild; ch.style.transform = ''; ch.style.opacity = 1; ch.style.visibility = 'visible' }
      for (const e of course.querySelectorAll('.sb-gname')) { e.style.opacity = 1; e.style.visibility = 'visible' }
      return null
    }
    const cam = camAt(tt), Z = cam.Z, zoomed = Z > 1.0005
    // while the camera is zoomed the lessons are scaled far past the stage and most of them are hidden or faded, so none of them takes a
    // click or Tab until the camera is back at zoom 1 (the widen's end); from there every lesson is on screen and works as in the course view
    if (course.inert !== zoomed) course.inert = zoomed
    const tx = cam.x - Z * p9().x - geo.courseOff.x, ty = cam.y - Z * p9().y - geo.courseOff.y
    course.style.transformOrigin = '0 0'
    course.style.transform = zoomed || Math.abs(tx) > 0.05 || Math.abs(ty) > 0.05 ? `translate(${tx.toFixed(2)}px,${ty.toFixed(2)}px) scale(${Z.toFixed(5)})` : ''
    // the turn: chips, road and part names take the course view's own colours as the ground goes blue; Lessons 1 to 8 come up to full
    const m = smooth(span(turn.start, turn.start + 0.45, tt)), head = headAt(tt)
    // chip 9's number shows only as the page has nearly gone, so the page's own text never lies over it
    const hide9 = tt < pb.end ? 1 - smooth(span(0.8, 0.95, cam.u)) : 0
    const lit8 = smooth(span(nb.start - 0.3, nb.start, tt)) * (1 - smooth(span(wd.start + 0.1, wd.start + 0.4, tt)))
    chips.forEach((b, i) => {
      const n = i + 1, s = b.firstChild.style, [fa, fb, k] = chipLook(n, tt, head), A = LOOK[fa], Bk = LOOK[fb]
      const ring = mixC(mixC(A[1], Bk[1], k), RING, m), inset = lerp(lerp(A[3], Bk[3], k), 0, m)
      s.backgroundColor = mixC(mixC(A[0], Bk[0], k), BP, m); s.borderColor = ring; s.color = mixC(mixC(mixC(A[2], Bk[2], k), '#fff', n === 9 ? hide9 : 0), BPINK, m)
      s.boxShadow = inset > 0.01 ? `inset 0 0 0 ${inset.toFixed(2)}px ${ring}` : 'none'
      let op = n <= DIM_TO ? lerp(n === 8 ? lerp(DIM_OP, 1, lit8) : DIM_OP, 1, m) : 1
      if (zoomed) { const p = onStage(cam, chipPos[i]), r = geo.chipR * Z; op *= edge(p.x - r, p.y - r, p.x + r, p.y + r, H) }
      s.transform = ''; s.opacity = op.toFixed(3); s.visibility = op > 0.003 ? 'visible' : 'hidden'
    })
    course.querySelectorAll('.sb-gname').forEach((e, gi) => {
      const st = nameAt(gi, tt), bx = geo.nameBox[gi]
      let op = st.op
      if (zoomed && op > 0) { const p = onStage(cam, bx); op *= edge(p.x, p.y, p.x + bx.w * Z, p.y + bx.h * Z, H) }
      e.style.color = mixC(mixC('var(--wr-ink)', 'var(--wr-red)', st.red), BPINK, m)
      e.style.opacity = op.toFixed(3); e.style.visibility = op > 0.003 ? 'visible' : 'hidden'
    })
    const rp = course._road.firstChild
    if (rp) { rp.style.stroke = mixC('var(--line-strong,#d3cdc4)', RING, m); rp.style.strokeOpacity = lerp(1, 0.7, m).toFixed(3); rp.style.strokeWidth = (lerp(3, 2, m) / Z).toFixed(4) }
    // the stroke: on the road behind chip 9 as the camera widens, its head walking forward, gone in the turn
    const so = smooth(span(wd.start, wd.start + 0.45 * (wd.end - wd.start), tt)) * (1 - smooth(span(turn.start, turn.end, tt)))
    const sp = course._stroke.firstChild
    course._stroke.style.visibility = so > 0.003 ? 'visible' : 'hidden'; course._stroke.style.opacity = so.toFixed(3)
    if (sp) { sp.style.strokeWidth = (3 / Z).toFixed(4); sp.style.strokeDasharray = `${head.toFixed(1)} ${(geo.roadLen + 10).toFixed(1)}` }
    return cam
  }
  // the titles read in the middle, under their chips on the stage (not scaled by the camera): 8, 9 and 10 while the camera holds on
  // them, then each part opener through its hold; inside the stage, never cut
  function renderTags(tt, cam) {
    const nb = BEAT.neighbours, wd = BEAT.widen
    tags.forEach((e, i) => {
      const n = TAGGED[i], big = NEIGHBOURS.includes(n), hold = BEAT['hold-' + n]
      const op = !cam ? 0 : big ? smooth(span(nb.start - 0.25, nb.start + 0.05, tt)) * (1 - smooth(span(wd.start, wd.start + 0.2, tt)))
        : hold ? smooth(span(hold.start - 0.15, hold.start, tt)) * (1 - smooth(span(hold.end, hold.end + 0.15, tt))) : 0
      if (op < 0.003) { e.style.visibility = 'hidden'; e.style.opacity = 0; return }
      // widths fixed for the beat (from the neighbours' zoom, not the moving one), so a title's text never reflows as it fades in
      const p = onStage(cam, chipPos[n - 1]), r = geo.chipR * cam.Z, gap = Math.abs(chipPos[9].x - chipPos[8].x) * geo.ZN
      const tw = big ? Math.max(40, Math.min(geo.courseWide ? 200 : 110, gap - 8)) : geo.courseWide ? chips[n - 1].offsetWidth : 130
      const left = clamp(big || geo.courseWide ? p.x - tw / 2 : p.x - r, 2, Math.max(2, W - tw - 2))
      e.classList.toggle('big', big)
      e.style.width = tw + 'px'
      e.style.transform = `translate(${left.toFixed(1)}px,${(p.y + r + (big ? 10 : 5)).toFixed(1)}px)`
      e.style.opacity = op.toFixed(3); e.style.visibility = 'visible'
    })
    // where a title shown in the middle would run into the row below (the neighbours' titles on a narrow phone, about 320 px), the chips
    // it would cover step back while it shows (fully from a 2 px overlap); an overlap up to 1.5 px (an edge contact, inside the line's
    // own leading) leaves the chip as it is
    const lines = []
    tags.forEach(e => {
      if (e.style.visibility !== 'visible') return
      const rg = document.createRange(); rg.selectNodeContents(e)
      for (const r of rg.getClientRects()) lines.push([r, +e.style.opacity])
    })
    if (!lines.length) return
    chips.forEach((b, i) => {
      const s = b.firstChild.style
      if (TAGGED.includes(i + 1) || s.visibility !== 'visible') return
      const c = b.firstChild.getBoundingClientRect()
      let k = 0
      for (const [r, o] of lines) {
        const ov = Math.min(Math.min(r.right, c.right) - Math.max(r.left, c.left), Math.min(r.bottom, c.bottom) - Math.max(r.top, c.top))
        k = Math.max(k, o * clamp((ov - 1.5) * 2))
      }
      if (k > 0) { const op = +s.opacity * (1 - k); s.opacity = op.toFixed(3); s.visibility = op > 0.003 ? 'visible' : 'hidden' }
    })
  }
  function courseAtRest() {
    clearWalk()
    course.style.visibility = 'visible'; course.style.opacity = 1
    chips.forEach(b => { const ch = b.firstChild; ch.style.transform = ''; ch.style.opacity = 1; ch.style.visibility = 'visible'; const ttl = b.children[1]; if (ttl) { ttl.style.opacity = 1; ttl.style.visibility = 'visible' } })
    for (const e of course.querySelectorAll('.sb-gname, .sb-hintc')) { e.style.opacity = 1; e.style.visibility = 'visible' }
    course._road.style.opacity = 1; course._road.style.visibility = 'visible'
  }

  // ---------- the preview card ----------
  function pvHtml(n) {
    const L = LESSONS[n - 1]
    let s = `<button type="button" class="sb-close" aria-label="Close">×</button>`
    s += `<h3 class="sb-pv-h" id="${pvId}" tabindex="-1"><span class="sb-pv-e"><span class="sb-pv-k">Lesson ${n}</span><span class="sb-pv-g" data-group="${L.group}">${esc(GROUP[L.group])}</span></span><span class="sb-pv-t">${esc(L.title)}</span></h3>`
    s += `<p class="sb-pv-sec">What this lesson teaches</p><ul class="sb-pv-topics">${L.topics.map(x => `<li>${mixedHtml(x)}</li>`).join('')}</ul>`
    s += `<p class="sb-pv-by">By the end of it you will be able to make sentences such as</p>`
    s += L.preview.map(id => { const r = ROWS[id]; return `<p class="sb-pv-ex"><span lang="to" data-row="${r.id}">${esc(r.to)}</span><span class="e" data-row="${r.id}">${esc(r.en)}</span></p>` }).join('')
    s += `<div class="sb-nav"><button type="button" class="sb-btn" data-go="-1"${n === 1 ? ' hidden' : ''}>← Lesson ${n - 1}</button><a class="sb-start" href="${esc(opt.lessonHref(n))}" data-lesson-link="${n}">Start Lesson ${n}</a><button type="button" class="sb-btn" data-go="1"${n === 52 ? ' hidden' : ''}>Lesson ${n + 1} →</button></div>`
    s += `<p class="sb-keys">Use ← and → to move between lessons.</p>`
    return s
  }
  function renderPv(announce) {
    if (!pvOpen) {
      pv.hidden = true
      if (pv.parentNode !== root) root.insertBefore(pv, live)
      chips.forEach(b => b.setAttribute('aria-expanded', 'false'))
      root.classList.remove('has-pv', 'is-docked')
      return
    }
    const L = LESSONS[selected - 1]
    pv.innerHTML = pvHtml(selected)
    pv.hidden = false
    chips.forEach(b => b.setAttribute('aria-expanded', +b.dataset.n === selected ? 'true' : 'false'))
    root.classList.add('has-pv')
    if (announce) live.textContent = `Lesson ${L.n}: ${L.title}. ${L.topics.length} topics and ${L.preview.length} example sentences.`
    placePv()
  }
  function placePv() {
    if (!pvOpen) return
    if (!geo.courseWide) {
      // a sheet under the chosen lesson's row, so the lesson, its row and the card are seen together
      root.classList.remove('is-docked')
      pv.style.left = pv.style.right = pv.style.top = ''
      const row = chips[selected - 1].parentNode
      if (pv.previousSibling !== row || pv.parentNode !== row.parentNode) row.after(pv)
      return
    }
    root.classList.add('is-docked')
    if (pv.parentNode !== root) root.insertBefore(pv, live)
    // docked on the side away from the lesson, so the lesson and its focus ring are never under the card
    const x = chipPos[selected - 1].x + geo.courseOff.x
    const right = x < W / 2
    const pad = parseFloat(getComputedStyle(panel).paddingRight) || 0
    pv.style.top = (panel.offsetTop + stage.offsetTop + 8) + 'px'
    pv.style.left = right ? '' : pad + 'px'
    pv.style.right = right ? pad + 'px' : ''
  }
  function revealPv() {
    // the card is on screen: scroll the least needed to show it (its top first if it is taller than the screen)
    const r = pv.getBoundingClientRect(), vh = window.innerHeight || 800
    if (r.top < 0 || r.bottom > vh) {
      const dy = r.height > vh - 16 ? r.top - 8 : (r.top < 0 ? r.top - 8 : r.bottom - vh + 8)
      window.scrollBy({ top: dy, behavior: 'instant' })
    }
  }
  function select(n, how = {}) {
    n = clamp(n, 1, 52)
    if (mode !== 'end') finish(false)
    selected = n; pvOpen = true
    renderPv(how.announce !== false)
    if (how.focusChip) chips[n - 1].focus({ preventScroll: true })
    if (how.focusPv) pv.querySelector('.sb-pv-h').focus({ preventScroll: true })
    if (how.reveal !== false) revealPv()
  }
  function closePv(focusChip = true) {
    pvOpen = false
    renderPv(false)
    if (focusChip && selected) { chips[selected - 1].focus({ preventScroll: true }); const r = chips[selected - 1].getBoundingClientRect(); if (r.top < 0 || r.bottom > innerHeight) chips[selected - 1].scrollIntoView({ block: 'center' }) }
  }

  // ---------- frame ----------
  function renderEndLayout() {
    root.classList.add('is-end', 'is-dark')
    ground.style.opacity = 1
    flag.hidden = true; chead.hidden = false; chead.style.opacity = 1
    // opacity as well as visibility: a drum face caught mid-spin keeps its own visibility:visible, which a hidden parent cannot override
    sent.style.visibility = 'hidden'; sent.style.opacity = 0; svg.innerHTML = ''; road.style.visibility = 'hidden'; road.style.opacity = 0
    renderPage(END + 1); renderTags(END + 1, null)
    stage.style.height = geo.courseWide ? geo.H + 'px' : ''
    courseAtRest()
    bPause.hidden = true; bSkip.hidden = true; bReplay.hidden = false
    renderPv(false)
  }
  function render(tt) {
    if (destroyed) return
    t = clamp(tt, 0, END)
    if (mode === 'end') { renderEndLayout(); return }
    root.classList.remove('is-end')
    const g = geo
    renderRoad(counterLesson(t))
    // chrome: white through the walk, blueprint blue from the turn on
    ground.style.opacity = smooth(span(BEAT.turn.start, BEAT.turn.start + 0.42, t))
    root.classList.toggle('is-dark', t >= BEAT.turn.start + 0.25)
    flag.hidden = t >= BEAT.turn.start + 0.25
    chead.hidden = !(t >= BEAT.course.start)
    chead.style.opacity = clamp((t - BEAT.course.start) / 0.3)
    bPause.hidden = false; bSkip.hidden = false; bReplay.hidden = false
    // stage height: one height on desktop; a phone grows to the course view as the pull-back starts
    const H = g.courseWide ? g.H : lerp(g.playH, Math.max(g.playH, g.courseH), smooth(span(BEAT.pullback.start, BEAT.pullback.start + 0.4, t)))
    stage.style.height = H + 'px'
    // the sentence
    if (t < PAGE + 0.5) {
      sent.style.visibility = 'visible'
      const s = renderSentence(Math.min(t, PAGE - 1e-3))
      const so = 1 - smooth(span(PAGE, PAGE + 0.4, t))
      sent.style.opacity = so
      drawLinks(s, lessonAt(Math.min(t, PAGE - 1e-3)), so)
      road.style.visibility = 'visible'; road.style.opacity = so
    } else { sent.style.visibility = 'hidden'; sent.style.opacity = 0; svg.innerHTML = ''; road.style.visibility = 'hidden'; road.style.opacity = 0 }
    renderPage(t)
    renderTags(t, renderCourse(t, H))
    pv.hidden = true
  }

  // ---------- clock ----------
  function tick(now) {
    raf = 0
    if (!playing || destroyed) return
    const dt = Math.min(0.1, (now - last) / 1000); last = now
    t += dt
    if (t >= END) { finish(false); return }
    render(t)
    rafReq(tick)
  }
  function play() {
    if (mode === 'end' || playing || destroyed) return
    playing = true; userPaused = false; autoPaused = false
    bPause.textContent = 'Pause'
    last = performance.now(); rafReq(tick)
  }
  function pause(byUser, auto) {
    if (byUser) userPaused = true
    if (auto && playing) autoPaused = true
    playing = false; if (raf) { cancelAnimationFrame(raf); raf = 0 }
    bPause.textContent = 'Play'
  }
  function finish() {
    pause(false); mode = 'end'; t = END
    render(END)
  }
  function replay() {
    pvOpen = false; renderPv(false)
    mode = 'play'; t = 0; segIdx = -1; flagN = -1
    root.classList.remove('is-end', 'is-dark')
    render(0); play()
  }

  // ---------- events ----------
  const on = (target, type, fn, o) => { target.addEventListener(type, fn, o); cleanups.push(() => target.removeEventListener(type, fn, o)) }
  const cleanups = []
  on(bPause, 'click', () => { if (playing) pause(true); else play() })
  on(bReplay, 'click', () => replay())
  on(bSkip, 'click', () => { finish(); bReplay.focus({ preventScroll: true }) })
  on(course, 'click', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    const n = +b.dataset.n
    if (pvOpen && n === selected && mode === 'end') { closePv(true); return }
    select(n, { announce: true })
  })
  on(course, 'focusin', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    // finishing re-lays the course out at rest, so a lesson focused mid-play is brought back into the window if the change moved it out
    if (mode !== 'end') { finish(); const r = b.getBoundingClientRect(); if (r.top < 0 || r.bottom > innerHeight) b.scrollIntoView({ block: 'nearest' }) }
    // while the card is open, the focused lesson becomes the open one, so the card docks away from it and never covers it;
    // with the card closed (Escape, ×) focus moves through the course without opening it
    if (pvOpen && +b.dataset.n !== selected) select(+b.dataset.n, { announce: false, reveal: false })
  })
  function rowStep(n, d) {
    const rows = geo.rowsOf, ri = rows.findIndex(r => r.includes(n)), to = rows[ri + d]
    if (!to) return null
    const x = chipPos[n - 1].x
    return to.reduce((best, m) => Math.abs(chipPos[m - 1].x - x) < Math.abs(chipPos[best - 1].x - x) ? m : best, to[0])
  }
  on(course, 'keydown', ev => {
    const b = ev.target.closest('.sb-ls'); if (!b) return
    // a click or tap opens the card but leaves focus on the lesson, so Escape must close it from here too
    if (ev.key === 'Escape' && pvOpen) { ev.preventDefault(); closePv(true); return }
    const n = +b.dataset.n
    const go ={ ArrowLeft: n - 1, ArrowRight: n + 1, ArrowUp: rowStep(n, -1), ArrowDown: rowStep(n, 1), Home: 1, End: 52 }[ev.key]
    if (ev.key in { ArrowLeft: 1, ArrowRight: 1, ArrowUp: 1, ArrowDown: 1, Home: 1, End: 1 }) {
      ev.preventDefault()
      if (go != null && go >= 1 && go <= 52) { if (pvOpen) select(go, { focusChip: true, reveal: false }); else chips[go - 1].focus({ preventScroll: true }); const r = chips[go - 1].getBoundingClientRect(); if (r.top < 0 || r.bottom > innerHeight) chips[go - 1].scrollIntoView({ block: 'center' }) }
      return
    }
    if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); select(n, { focusPv: true, announce: true }) }
  })
  on(pv, 'click', ev => {
    const b = ev.target.closest('button, a'); if (!b) return
    if (b.classList.contains('sb-close')) { closePv(true); return }
    if (b.dataset.go) { const d = b.dataset.go; select(selected + +d, { announce: true }); const nb = pv.querySelector(`[data-go="${d}"]`); (nb && !nb.hidden ? nb : pv.querySelector('.sb-pv-h')).focus({ preventScroll: true }); return }
    if (b.dataset.lessonLink && opt.onNavigate && !(ev.metaKey || ev.ctrlKey || ev.shiftKey || ev.altKey)) { ev.preventDefault(); opt.onNavigate(b.getAttribute('href'), ev) }
  })
  // Shift+Tab out of the card onto a lesson before it closes the card (a click on a lesson is left to the click handler)
  let lastPointer = -1e9
  on(root, 'pointerdown', () => { lastPointer = performance.now() }, true)
  on(pv, 'focusout', ev => {
    const to = ev.relatedTarget
    if (!pvOpen || !to || pv.contains(to) || !to.closest || !to.closest('.sb-ls') || !root.contains(to) || performance.now() - lastPointer < 500) return
    if (to.compareDocumentPosition(pv) & Node.DOCUMENT_POSITION_FOLLOWING) closePv(false)
  })
  // 3: Escape closes an open card wherever focus is in the module, or with focus nowhere (Safari leaves it there after a click)
  on(document, 'keydown', ev => {
    if (ev.key !== 'Escape' || !pvOpen || ev.defaultPrevented) return
    const a = document.activeElement
    if (a && a !== document.body && a !== document.documentElement && !root.contains(a)) return
    ev.preventDefault(); closePv(true)
  })
  on(pv, 'keydown', ev => {
    if (ev.key === 'Escape') { ev.preventDefault(); closePv(true); return }
    if (ev.key === 'ArrowLeft' || ev.key === 'ArrowRight') {
      ev.preventDefault(); const d = ev.key === 'ArrowLeft' ? -1 : 1
      if (selected + d >= 1 && selected + d <= 52) select(selected + d, { focusPv: true, announce: true })
    }
  })
  // start when the section is mostly in view; pause when it leaves
  let io = null
  if (!reduced && typeof IntersectionObserver === 'function') {
    io = new IntersectionObserver(entries => {
      for (const en of entries) {
        const vh = window.innerHeight || 1
        const mostly = en.intersectionRatio >= opt.startRatio || en.intersectionRect.height >= vh * 0.6
        inView = mostly || (inView && en.intersectionRatio >= 0.2)
        if (mostly && mode === 'play' && !playing && !userPaused && !document.hidden) play()
        else if (en.intersectionRatio < 0.2 && playing) pause(false, true)
      }
    }, { threshold: [0, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1] })
    io.observe(panel)
  }
  // a hidden tab pauses; coming back resumes only a pause the module made itself, with the panel still in view and no Pause pressed
  on(document, 'visibilitychange', () => {
    if (document.hidden) { if (playing) pause(false, true) }
    else if (autoPaused && inView && !userPaused && mode === 'play' && !playing) play()
  })
  let ro = null
  const relayout = () => { if (destroyed) return; const w = stage.clientWidth; if (Math.abs(w - W) < 1 && geo) return; sizeCache.clear(); classify(); groupW = groupWidths(); segIdx = -1; stopX = null; flagN = -1; render(t) }
  if (typeof ResizeObserver === 'function') { ro = new ResizeObserver(() => relayout()); ro.observe(root) }

  // ---------- start ----------
  classify(); groupW = groupWidths()
  if (mode === 'end') { finish() } else render(0)
  if (document.fonts && document.fonts.status !== 'loaded') document.fonts.ready.then(() => { if (!destroyed) { sizeCache.clear(); courseKey = ''; classify(); groupW = groupWidths(); segIdx = -1; stopX = null; flagN = -1; render(t) } })

  const controller = {
    el, root,
    get time() { return t }, get mode() { return mode }, get playing() { return playing }, get selected() { return pvOpen ? selected : 0 }, get reduced() { return reduced },
    get cardOpen() { return pvOpen }, get timeline() { return timeline },
    get geometry() { return { ...geo, width: W } },
    seek(tt, o = {}) { if (mode === 'end') { mode = 'play'; pvOpen = false; renderPv(false); root.classList.remove('is-end', 'is-dark') } pause(false); segIdx = -1; flagN = -1; render(tt); if (o.asPlaying) bPause.textContent = 'Pause'; return t },
    play, pause: () => pause(true), replay, skip: () => finish(), select: n => select(n, { announce: true }), close: () => closePv(false),
    destroy() {
      if (destroyed) return
      destroyed = true; pause(false)
      cleanups.forEach(f => f()); if (io) io.disconnect(); if (ro) ro.disconnect()
      root.remove(); instances.delete(controller)
      if (--styleRefs <= 0 && styleEl) { styleEl.remove(); styleEl = null; styleRefs = 0 }
    },
  }
  instances.add(controller)
  return controller
}

export function unmount(el) {
  for (const inst of [...instances]) if (!el || inst.el === el) inst.destroy()
}

export const data = DATA
export default { mount, unmount, TIMELINE }
